use crate::sql_lint::models::LintRuleMetadata;

pub(crate) const UNUSED_CTE_OUTPUT: LintRuleMetadata = LintRuleMetadata {
    code: "SQBRSQL042",
    message: "CTE output column is never read later in the model",
    remediation: "Remove the column from the CTE output, or read it in a later CTE or the final query.",
};
pub(crate) const RANKING_SORT_CAP: LintRuleMetadata = LintRuleMetadata {
    code: "SQBRSQL043",
    message: "Ranking window sorts by more expressions than max_ranking_order_by",
    remediation: "Order by the one or two columns that decide which row wins, then a unique row key as the final tie-breaker.",
};
pub(crate) const LONG_LITERAL: LintRuleMetadata = LintRuleMetadata {
    code: "SQBRSQL044",
    message: "String literal is longer than max_literal_length",
    remediation: "Define the value once as a constant and reference it with `@const`, or shorten it.",
};
pub(crate) const REPEATED_JSON_PARSE: LintRuleMetadata = LintRuleMetadata {
    code: "SQBRSQL045",
    message: "JSON payload is parsed more than once in one SELECT",
    remediation: "Parse the payload once in the CTE that reads it, for example `TRY_PARSE_JSON(value) AS payload`, and read every field from that column in a later step.",
};
pub(crate) const UNSTABLE_ROW_NUMBER_CODE: &str = "SQBRSQL018";
pub(crate) const UNPROVEN_RANKING_MESSAGE: &str =
    "Ranking window order is not proven unique within its partition";
pub(crate) const UNPROVEN_RANKING_REMEDIATION: &str = "PARTITION BY and ORDER BY must together cover a declared key of the ranked rows. End the ORDER BY with a unique tie-breaker column, or declare the key upstream. A key qualifies when it is a `unique` column audit on a column that is also non-null (a `not_null` audit or `nullable false`), or the `unique_key` of an incremental `merge` model or of a `delete_insert` model without a cursor; snapshot, append, microbatch and cursor-ranged `unique_key`s do not prove one row per key. If the rows have no unique column, build one in the upstream model from the columns that identify a row (for example `HASH(source_partition, source_offset, line_index) AS row_key`), declare it with a `unique` audit, and order by it last.";
/// SQBRSQL043 guidance before the `max_ranking_order_by` setting snippet.
pub(crate) const RANKING_SORT_GUIDANCE: &str = "Order by the one or two columns that decide which row wins, then a unique row key as the final tie-breaker. If the rows have no unique column, build one in the upstream model from the columns that identify a row (for example `HASH(source_partition, source_offset, line_index) AS row_key`) and declare it with a `unique` audit, so SQBRSQL018 can prove the order is deterministic. If the order genuinely needs more keys, raise `max_ranking_order_by` for the project.";
/// SQBRSQL044 guidance before the `max_literal_length` setting snippet.
pub(crate) const LONG_LITERAL_GUIDANCE: &str = "Define the value once as a constant and reference it with `@const`, in the narrowest scope that covers every use. (1) Only this model: add `constants (_status_pattern '<value>')` to its `MODEL (...)` header and write `@const(\"_status_pattern\")`. (2) Other files use the same value: declare `CONSTANT (name status_pattern, value '<value>');` in `_sqlbuild/_constants/` of the nearest folder that contains every use when they all sit directly in that folder, or in its `_sqlbuild/constants/` to include subfolders, and write `@const(\"status_pattern\")`. (3) Use top-level `constants/` only when the value is needed project-wide. Otherwise shorten the literal.";
pub(crate) const RULES_THRESHOLDS_SECTION: &str = "rules.thresholds";
pub(crate) const MAX_RANKING_ORDER_BY_KEY: &str = "max_ranking_order_by";
pub(crate) const MAX_LITERAL_LENGTH_KEY: &str = "max_literal_length";
pub(crate) const DISTINCT_UNUSED_REMEDIATION: &str = "This CTE uses SELECT DISTINCT, so the column still decides which rows are kept. Make the deduplication independent of the column, or restructure the CTE so it outputs only what later steps read.";
pub(crate) const GROUP_KEY_UNUSED_REMEDIATION: &str = "Drop the column from the CTE output but keep it in GROUP BY; the grouping grain stays the same.";
pub(crate) const GROUP_BY_ALL_UNUSED_REMEDIATION: &str = "This CTE uses GROUP BY ALL, so the column is part of the grouping grain. List the grouping columns explicitly and keep this one in GROUP BY, then drop it from the output.";
/// Expression kinds that compute one value per input row without changing the row set.
pub(crate) const ROW_NEUTRAL_EXPRESSIONS: &[&str] = &[
    "literal",
    "boolean",
    "null",
    "identifier",
    "column",
    "paren",
    "dot",
    "subscript",
    "data_type",
    "interval",
    "cast",
    "try_cast",
    "safe_cast",
    "collation",
    "case",
    "and",
    "or",
    "not",
    "neg",
    "add",
    "sub",
    "mul",
    "div",
    "mod",
    "eq",
    "neq",
    "lt",
    "lte",
    "gt",
    "gte",
    "like",
    "i_like",
    "is",
    "is_null",
    "is_true",
    "is_false",
    "in",
    "between",
    "null_safe_eq",
    "bitwise_and",
    "bitwise_or",
    "bitwise_xor",
    "concat",
    "concat_ws",
    "substring",
    "upper",
    "lower",
    "length",
    "trim",
    "replace",
    "left",
    "right",
    "lpad",
    "rpad",
    "split",
    "split_part",
    "regexp_replace",
    "initcap",
    "position",
    "contains",
    "starts_with",
    "ends_with",
    "abs",
    "round",
    "floor",
    "ceil",
    "greatest",
    "least",
    "coalesce",
    "null_if",
    "if_func",
    "if_null",
    "nvl",
    "nvl2",
    "decode",
    "date_add",
    "date_diff",
    "date_trunc",
    "timestamp_trunc",
    "extract",
    "to_date",
    "to_timestamp",
    "to_char",
    "to_number",
    "date",
    "year",
    "month",
    "last_day",
    "struct_extract",
];
/// Generic function names known to be deterministic scalar functions in supported dialects.
pub(crate) const DETERMINISTIC_SCALAR_FUNCTIONS: &[&str] = &[
    "ABS",
    "ARRAY_SIZE",
    "CEIL",
    "CHARINDEX",
    "COALESCE",
    "CONCAT",
    "CONCAT_WS",
    "DATEADD",
    "DATEDIFF",
    "DATE_ADD",
    "DATE_DIFF",
    "DATE_PART",
    "DATE_TRUNC",
    "DAY",
    "DIV0",
    "FLOOR",
    "GREATEST",
    "HOUR",
    "IFF",
    "IFNULL",
    "LEAST",
    "LEFT",
    "LENGTH",
    "LOWER",
    "LPAD",
    "LTRIM",
    "MD5",
    "MOD",
    "MONTH",
    "NULLIF",
    "NVL",
    "NVL2",
    "POWER",
    "REGEXP_REPLACE",
    "REPLACE",
    "RIGHT",
    "ROUND",
    "RPAD",
    "RTRIM",
    "SPLIT_PART",
    "SQRT",
    "STRPOS",
    "SUBSTR",
    "SUBSTRING",
    "TO_CHAR",
    "TO_DATE",
    "TO_VARCHAR",
    "TRIM",
    "TRUNC",
    "UPPER",
    "YEAR",
    "ZEROIFNULL",
];
pub(crate) const DEFAULT_MAX_LITERAL_LENGTH: usize = 100;
pub(crate) const DEFAULT_MAX_RANKING_ORDER_BY: usize = 5;
pub(crate) const TIE_SENSITIVE_FUNCTIONS: [&str; 3] = ["ROW_NUMBER", "FIRST_VALUE", "LAST_VALUE"];
pub(crate) const MIN_REMOVABLE_OUTPUTS: usize = 2;
pub(crate) const INTERPOLATION_SENTINEL_PREFIXES: [&str; 3] = [
    "__sqb_lint_",
    "__sqlbuild_audit_parameter_",
    "__sqlbuild_context_parameter_",
];
pub(crate) const FIRST_ROW: &str = "1";
