"""Constants for the lint and format layer."""

from __future__ import annotations

from sqlbuild.lint.types import LintSeverity

LINT_ENGINE_SQLBUILD: str = "sqlbuild"
LINT_ENGINE_NATIVE: str = "native"

VIOLATION_SEVERITY_FAULT: LintSeverity = LintSeverity.FAULT
VIOLATION_SEVERITY_WARNING: LintSeverity = LintSeverity.WARNING

HEADER_KIND_MODEL: str = "MODEL"
HEADER_KIND_SCENARIO: str = "SCENARIO"
HEADER_KIND_TEST: str = "TEST"
HEADER_KIND_AUDIT: str = "AUDIT"
HEADER_KIND_FUNCTION: str = "FUNCTION"
HEADER_KIND_ENUM: str = "ENUM"
HEADER_KIND_CONSTANT: str = "CONSTANT"
HEADER_KIND_HOOK: str = "HOOK"
HEADER_KIND_SCHEMA: str = "SCHEMA"

DSL_HEADER_KINDS: frozenset[str] = frozenset(
    {
        HEADER_KIND_MODEL,
        HEADER_KIND_SCENARIO,
        HEADER_KIND_TEST,
        HEADER_KIND_AUDIT,
        HEADER_KIND_FUNCTION,
        HEADER_KIND_ENUM,
        HEADER_KIND_CONSTANT,
        HEADER_KIND_HOOK,
        HEADER_KIND_SCHEMA,
    }
)

IDENTIFIER_SEPARATOR_CHARACTER: str = "_"

DESCRIPTION_HEADER_KINDS: frozenset[str] = frozenset({HEADER_KIND_MODEL, HEADER_KIND_SCENARIO})
DESCRIPTION_REQUIRED_HEADER_KINDS: frozenset[str] = frozenset({HEADER_KIND_MODEL})

DEFAULT_MAX_DESCRIPTION_LINES: int = 10

LINT_DIRECTORY_NAMES: tuple[str, ...] = (
    "models",
    "tests",
    "audits",
    "functions",
    "enums",
    "constants",
    "hooks",
    "schemas",
)

RULE_DESCRIPTION_PRESENT: str = "description-present"
RULE_DESCRIPTION_LENGTH: str = "description-length"
RULE_LEADING_COMMENT_DESCRIPTION: str = "leading-comment-description"
RULE_HEADER_WHITESPACE: str = "header-whitespace"
RULE_HEADER_PARSE: str = "header-parse"

PROJECT_CONFIG_FILENAME_KEY: str = "sqlbuild_project.toml"
LINT_SECTION_KEY: str = "lint"
MAX_DESCRIPTION_LINES_KEY: str = "max_description_lines"

ADAPTER_DIALECT_TRANSLATIONS: dict[str, str] = {
    "duckdb": "duckdb",
    "motherduck": "duckdb",
    "snowflake": "snowflake",
    "bigquery": "bigquery",
    "databricks": "databricks",
    "postgres": "postgres",
    "sqlserver": "tsql",
}
ADAPTER_CONFIG_KEY: str = "adapter"

SQL_QUOTE_CHARACTERS: frozenset[str] = frozenset({"'", '"'})
SQL_ESCAPE_CHARACTER: str = "\\"
SINGLE_QUOTE_CHARACTER: str = "'"
OPENING_PAREN_CHARACTER: str = "("
CLOSING_PAREN_CHARACTER: str = ")"
IDENTIFIER_EXTRA_CHARACTER: str = "_"
INTERPOLATION_NAME_EXTRA_CHARACTERS: frozenset[str] = frozenset({"_", ":", "."})
SENTINEL_TEMPLATE: str = "__sqb_lint_{index}__"
EXPECTED_SENTINEL_OCCURRENCES: int = 1
TEMPLATE_INTERPOLATION_START: str = "${"
TEMPLATE_INTERPOLATION_END: str = "}"

GENERATED_SQL_MESSAGE_TEMPLATE: str = "(in SQL generated by {token})"
GENERATED_SQL_MESSAGE_SUFFIX: str = "(in generated SQL)"

LINE_FEED: str = "\n"
CARRIAGE_RETURN_LINE_FEED: str = "\r\n"
