"""Constants for the lint and format layer."""

from __future__ import annotations

LINT_ENGINE_SQLBUILD: str = "sqlbuild"
LINT_ENGINE_SQRUFF: str = "sqruff"

VIOLATION_SEVERITY_FAULT: str = "fault"
VIOLATION_SEVERITY_WARNING: str = "warning"

HEADER_KIND_MODEL: str = "MODEL"
HEADER_KIND_SCENARIO: str = "SCENARIO"
HEADER_KIND_TEST: str = "TEST"
HEADER_KIND_AUDIT: str = "AUDIT"
HEADER_KIND_FUNCTION: str = "FUNCTION"
HEADER_KIND_ENUM: str = "ENUM"
HEADER_KIND_CONSTANT: str = "CONSTANT"
HEADER_KIND_HOOK: str = "HOOK"

DSL_HEADER_KINDS: frozenset[str] = frozenset(
    {
        HEADER_KIND_MODEL,
        HEADER_KIND_SCENARIO,
        HEADER_KIND_TEST,
        HEADER_KIND_AUDIT,
        HEADER_KIND_FUNCTION,
        HEADER_KIND_ENUM,
        HEADER_KIND_CONSTANT,
        HEADER_KIND_HOOK,
    }
)

IDENTIFIER_SEPARATOR_CHARACTER: str = "_"

DESCRIPTION_HEADER_KINDS: frozenset[str] = frozenset({HEADER_KIND_MODEL, HEADER_KIND_SCENARIO})
DESCRIPTION_REQUIRED_HEADER_KINDS: frozenset[str] = frozenset({HEADER_KIND_MODEL})

DEFAULT_MAX_DESCRIPTION_LINES: int = 10
DEFAULT_SQRUFF_CONFIG_PATH: str = ".sqruff"

LINT_DIRECTORY_NAMES: tuple[str, ...] = (
    "models",
    "tests",
    "audits",
    "functions",
    "enums",
    "constants",
    "hooks",
)

DEFAULT_SQRUFF_CONFIG_CONTENT: str = """\
[core]
dialect = "snowflake"
templater = "jinja"
"""

RULE_DESCRIPTION_PRESENT: str = "description-present"
RULE_DESCRIPTION_LENGTH: str = "description-length"
RULE_LEADING_COMMENT_DESCRIPTION: str = "leading-comment-description"
RULE_HEADER_WHITESPACE: str = "header-whitespace"
RULE_HEADER_PARSE: str = "header-parse"

PROJECT_CONFIG_FILENAME_KEY: str = "sqlbuild_project.toml"
LINT_SECTION_KEY: str = "lint"
SQRUFF_ENABLED_KEY: str = "sqruff"
SQRUFF_CONFIG_PATH_KEY: str = "sqruff_config"
MAX_DESCRIPTION_LINES_KEY: str = "max_description_lines"

ADAPTER_DIALECT_TRANSLATIONS: dict[str, str] = {
    "duckdb": "duckdb",
    "motherduck": "duckdb",
    "snowflake": "snowflake",
    "bigquery": "bigquery",
    "databricks": "databricks",
    "postgres": "postgres",
    "sqlserver": "tsql",
}
SQRUFF_CONFIG_SECTION: str = "core"
SQRUFF_CONFIG_DIALECT_KEY: str = "dialect"
ADAPTER_CONFIG_KEY: str = "adapter"
DEFAULT_SQRUFF_CONFIG_TEMPLATE: str = '[core]\ndialect = "{dialect}"\n'
FALLBACK_SQRUFF_DIALECT: str = "ansi"
CONFIG_QUOTE_CHARACTERS: frozenset[str] = frozenset({"'", '"'})
MINIMUM_QUOTED_LENGTH: int = 2

SQL_QUOTE_CHARACTERS: frozenset[str] = frozenset({"'", '"'})
SQL_ESCAPE_CHARACTER: str = "\\"
SINGLE_QUOTE_CHARACTER: str = "'"
OPENING_PAREN_CHARACTER: str = "("
CLOSING_PAREN_CHARACTER: str = ")"
IDENTIFIER_EXTRA_CHARACTER: str = "_"
INTERPOLATION_NAME_EXTRA_CHARACTERS: frozenset[str] = frozenset({"_", ":", "."})
SENTINEL_TEMPLATE: str = "__sqb_lint_{index}__"
EXPECTED_SENTINEL_OCCURRENCES: int = 1
TEMPLATE_INTERPOLATION_START: str = "${"
TEMPLATE_INTERPOLATION_END: str = "}"

SQRUFF_EXPECTED_EXIT_CODES: frozenset[int] = frozenset({0, 1})
SQRUFF_DIALECTS_COMMAND: str = "dialects"
SQRUFF_RANGE_KEY: str = "range"
SQRUFF_START_KEY: str = "start"
SQRUFF_LINE_KEY: str = "line"
SQRUFF_CHARACTER_KEY: str = "character"
SQRUFF_MINIMUM_POSITION: int = 1

GENERATED_SQL_MESSAGE_TEMPLATE: str = "(in SQL generated by {token})"
GENERATED_SQL_MESSAGE_SUFFIX: str = "(in generated SQL)"

LINE_FEED: str = "\n"
CARRIAGE_RETURN_LINE_FEED: str = "\r\n"
