"""Output capture delivery defaults."""

DEFAULT_OUTPUT_BATCH_SIZE: int = 64
DEFAULT_OUTPUT_MAX_RECORD_BYTES: int = 64 * 1024
DEFAULT_OUTPUT_QUEUE_CAPACITY: int = 1024
DEFAULT_OUTPUT_SHUTDOWN_TIMEOUT_SECONDS: float = 2.0
MIN_OUTPUT_RECORD_BYTES: int = 4
OUTPUT_LINE_EVENT_TYPE: str = "output_line"
OUTPUT_LOSS_SUMMARY_EVENT_TYPE: str = "output_loss_summary"
OUTPUT_RECORD_TYPE: str = "output"
OUTPUT_LOSS_SUMMARY_RECORD_TYPE: str = "loss_summary"
