"""Output capture delivery defaults."""

DEFAULT_OUTPUT_BATCH_SIZE: int = 64
DEFAULT_OUTPUT_MAX_RECORD_BYTES: int = 64 * 1024
DEFAULT_OUTPUT_QUEUE_CAPACITY: int = 1024
DEFAULT_OUTPUT_SHUTDOWN_TIMEOUT_SECONDS: float = 2.0
MIN_OUTPUT_RECORD_BYTES: int = 4
