"""Native model analysis session constants."""

ANALYSIS_DEFERRAL_SITE: str = "analysis_session"
DEFERRAL_NO_COMPACT_ANALYSIS: str = "no_compact_analysis"
DEFERRAL_NO_CATALOG: str = "no_analysis_catalog"
DEFERRAL_SESSION: str = "session"
DEFERRAL_LEGACY_ANALYSIS: str = "legacy_analysis"
DEFERRAL_ENRICHMENT: str = "input_enrichment"
DEFERRAL_DYNAMIC_PIVOT: str = "dynamic_pivot"
DEFERRAL_EXPRESSION_SHAPES: str = "expression_shapes"
DEFERRAL_ANALYSIS: str = "analysis"
DEFERRAL_ENRICH: str = "enrichment"
LINEAGE_NATIVE: str = "native"
LINEAGE_FACTS: str = "facts"
CONTRACT_DEFERRED: str = "deferred"
NATIVE_ANALYSIS_FAILURE_MESSAGE: str = "native compact query analysis failed"
NATIVE_SESSION_FAILURE_MESSAGE: str = "native model analysis failed; falling back"
NATIVE_SHAPES_FAILURE_MESSAGE: str = "native expression-source shape inference failed; falling back"
NULLABILITY_RULE_FIRST_ARG: str = "first_arg"
NULLABILITY_RULE_CONDITIONAL_RESULT: str = "conditional_result"
NATIVE_ANALYSIS_STORE_FILE_NAME: str = "model-analyses.bin"
NATIVE_ANALYSIS_STORE_VERSION: str = "native-model-analysis-store-v1"
NATIVE_ANALYSIS_STORE_FAILURE_MESSAGE: str = "native model analysis cache not read or saved"
