"""Private native kata engine bindings."""

def catalogue_json() -> str: ...
def evaluate_json(request_json: str) -> str: ...
def load_config_json(project_dir: str) -> str: ...
def selected_codes_json(request_json: str) -> str: ...
def render_owned_skill(content: str, input_fingerprint: str) -> str: ...
def skill_freshness(content: str | None, input_fingerprint: str) -> str: ...
