"""Private SQLBuild native engine bindings."""

from typing import TypedDict

BUILD_IDENTITY: str

class LintPreparationRequest(TypedDict):
    expanded: str
    before_expansion: str
    prior_sites: list[int]
    dialect: str

class ParsedRulesRequest:
    """Decoded built-in rules request held natively until it is evaluated once."""

def analyze_column_references_json(request_json: str) -> str: ...
def catalogue_json() -> str: ...
def evaluate_json(request_json: str) -> str: ...
def parse_rules_parts(
    request_json: bytes, model_jsons: list[bytes], model_digests: list[str]
) -> ParsedRulesRequest: ...
def evaluate_parsed_rules(parsed: ParsedRulesRequest) -> str: ...
def finalize_rule_findings_json(request_json: str) -> str: ...
def run_custom_host_json(spec_json: str) -> str: ...
def format_sql_json(request_json: str) -> str: ...
def format_sql_batch_json(request_json: str) -> str: ...
def query_fingerprint(sql: str, dialect: str) -> str: ...
def lint_sql_json(request_json: str) -> str: ...
def lint_sql_batch_json(request_json: str) -> str: ...
def prepare_lint_sql(
    request: LintPreparationRequest,
) -> tuple[str, list[tuple[str, int, int, int, int, str]], list[str]] | None: ...
def prepare_lint_sql_batch(
    requests: list[LintPreparationRequest],
) -> list[tuple[bool, tuple[str, list[tuple[str, int, int, int, int, str]], list[str]] | None]]: ...
def lint_backtick_identifiers(dialect: str) -> bool: ...
def load_config_json(project_dir: str) -> str: ...
def selected_codes_json(request_json: str) -> str: ...
def render_owned_skill(content: str, input_fingerprint: str) -> str: ...
def skill_freshness(content: str | None, input_fingerprint: str) -> str: ...
def match_model_headers(contents: list[str]) -> list[tuple[int, int, int] | None]: ...
def parse_model_headers(
    headers: list[str],
) -> list[tuple[dict[str, object] | None, list[tuple[str, int, int]] | None, str | None]]: ...
def tokenize_model_header(header: str) -> list[tuple[int, str, int]]: ...
def substitute_static_project_vars(
    sqls: list[str], variables: list[tuple[str, str]]
) -> list[tuple[int, str | None]]: ...
def extract_static_sql_references(
    sql: str,
) -> list[tuple[str, str, str | None, int | None]] | None: ...
