"""Function executor diagnostic codes."""

FUNCTION_TARGET_INVALID_CODE: str = "F001"
FUNCTION_PYTHON_UNSUPPORTED_CODE: str = "F002"
FUNCTION_TABLE_UNSUPPORTED_CODE: str = "F003"
FUNCTION_EXECUTION_FAILED_CODE: str = "F004"
FUNCTION_ENTRY_MISSING_CODE: str = "F005"
