default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: verify-quick
        name: make verify-quick
        entry: make verify-quick
        language: system
        pass_filenames: false

      - id: conventional-commit
        name: conventional commit message
        entry: uv run cz check --commit-msg-file
        language: system
        stages: [commit-msg]
