pub(crate) const CAST_TYPE_SEPARATOR_KEYWORD: &str = "AS";
pub(crate) const CLOSE_PARENTHESIS: &str = ")";
pub(crate) const LINT_API_VERSION: u32 = 1;
pub(crate) const OPEN_PARENTHESIS: &str = "(";
pub(crate) const POSITION_ARGUMENT_SEPARATOR: &str = ",";
pub(crate) const CTE_MACRO_PLACEHOLDER_LITERAL: &str = "1";
pub(crate) const POSTFIX_CAST_PREFIX_TOKEN_COUNT: usize = 2;
pub(crate) const RELATION_MODIFIER_KEYWORDS: [&str; 43] = [
    "ANTI",
    "APPLY",
    "ASOF",
    "AT",
    "BEFORE",
    "CHANGES",
    "CONNECT",
    "CROSS",
    "EXCEPT",
    "FETCH",
    "FINAL",
    "FOR",
    "FULL",
    "GROUP",
    "HAVING",
    "INNER",
    "INTERSECT",
    "JOIN",
    "LATERAL",
    "LEFT",
    "LIMIT",
    "MATCH_RECOGNIZE",
    "MINUS",
    "NATURAL",
    "OFFSET",
    "ON",
    "ORDER",
    "OUTER",
    "PASTE",
    "PIVOT",
    "POSITIONAL",
    "QUALIFY",
    "RETURNING",
    "RIGHT",
    "SAMPLE",
    "SEMI",
    "START",
    "TABLESAMPLE",
    "UNION",
    "UNPIVOT",
    "USING",
    "WHERE",
    "WINDOW",
];
