"""Destination-neutral event exporter delivery defaults."""

DEFAULT_EVENT_EXPORT_QUEUE_CAPACITY: int = 1024
DEFAULT_EVENT_EXPORT_SHUTDOWN_TIMEOUT_SECONDS: float = 2.0
DEFAULT_EVENT_EXPORT_INVOCATION_TIMEOUT_SECONDS: float = 1.0
DEFAULT_EVENT_EXPORT_NOTIFICATION_QUEUE_CAPACITY: int = 256
EVENT_EXPORTER_EVENT_PARAMETER_NAME: str = "event"
