"""Planner domain constants."""

from __future__ import annotations

MICROBATCH_START_SENTINEL: str = "__SQB_CURSOR_START__"
MICROBATCH_END_SENTINEL: str = "__SQB_CURSOR_END__"
METADATA_NAME_FILTER_LIMIT: int = 250
SCENARIO_HASH_PREFIX_LENGTH: int = 12
SCENARIO_SHORTENED_LOGICAL_HASH_LENGTH: int = 8
SCENARIO_DEFAULT_IDENTIFIER_LIMIT: int = 63
