"""Planner domain constants."""

from __future__ import annotations

PATH_SELECTOR_EXPLICIT_ROOT_ERROR: str = (
    "path selectors require an explicit root: use 'models/', 'tasks/', 'assets/', "
    "'checks/', or 'loaders/'"
)
MICROBATCH_START_SENTINEL: str = "__SQB_CURSOR_START__"
MICROBATCH_END_SENTINEL: str = "__SQB_CURSOR_END__"
METADATA_NAME_FILTER_LIMIT: int = 250
SCENARIO_ARTIFACT_PREFIX: str = "__sqb_"
SCENARIO_HASH_PREFIX_LENGTH: int = 12
SCENARIO_SHORTENED_LOGICAL_HASH_LENGTH: int = 8
SCENARIO_ARTIFACT_KINDS: tuple[str, ...] = ("source", "ref", "seed", "dbt_ref", "model")
SCENARIO_DEFAULT_IDENTIFIER_LIMIT: int = 63
SCENARIO_PLAN_INVALID_HASH_PREFIX: str = "S501"
SCENARIO_PLAN_HASH_COLLISION: str = "S502"
SCENARIO_PLAN_RELATION_COLLISION: str = "S503"
SCENARIO_PLAN_GRAPH_VALIDATION: str = "S504"
SCENARIO_PLAN_SQLGLOT_UNAVAILABLE: str = "S505"
SCENARIO_PLAN_SQLGLOT_PARSE: str = "S506"
SCENARIO_PLAN_UNKNOWN_SEED: str = "S507"
SCENARIO_PLAN_MISSING_FIXTURE_SQL: str = "S508"
SCENARIO_PLAN_MISSING_RELATION_TARGET: str = "S509"
SCENARIO_PLAN_INTERNAL: str = "S599"
