name = "loader_waffle_shop"
adapter = "duckdb"
default_target = "dev"

[connections.developer]
database = "loader_waffle_shop.duckdb"

[defaults]
materialized = "table"

[targets.dev]
connection = "developer"
schema = "main"
