from __future__ import annotations

from pathlib import Path

import pytest

from sqlbuild.compiler.compile.models import CompiledProject
from sqlbuild.integrations.dbt.helpers.graph import build_dbt_combined_graph
from sqlbuild.integrations.dbt.helpers.manifest import build_dbt_manifest_index
from sqlbuild.integrations.dbt.helpers.plan_orchestration import plan_dbt_interop_command
from sqlbuild.integrations.dbt.helpers.runner import DbtRunner
from sqlbuild.integrations.dbt.models import (
    DbtCliOptions,
    DbtCombinedGraph,
    DbtInteropPlan,
    DbtManifestIndex,
)
from tests.unit.src.sqlbuild.integrations.dbt._test_types import DbtPlanOrchestrationTestCase
from tests.unit.src.sqlbuild.integrations.dbt.helpers import (
    MappingDbtInvoker,
    build_compiled_project_with_model_specs,
    build_dbt_plan_mapping_invoker,
    build_manifest_data,
    build_manifest_model_node,
    extract_dbt_ls_excludes,
    extract_dbt_ls_selects,
)

_DBT_OPTIONS: DbtCliOptions = DbtCliOptions(project_dir=Path("/repo/dbt"), target="dev")
_FULL_DBT_OPTIONS: DbtCliOptions = DbtCliOptions(
    project_dir=Path("/repo/dbt"),
    profiles_dir=Path("/repo/profiles"),
    target="prod",
    target_path=Path("/repo/dbt-target"),
    vars='{"run_date":"2026-01-01"}',
    state=Path("/repo/state"),
    defer=True,
)
_MANIFEST_DATA: dict[str, object] = build_manifest_data(
    nodes=(
        build_manifest_model_node(
            unique_id="model.analytics.stg_orders",
            package_name="analytics",
            name="stg_orders",
            relation_name="analytics.stg_orders",
        ),
        build_manifest_model_node(
            unique_id="model.analytics.int_orders",
            package_name="analytics",
            name="int_orders",
            relation_name="analytics.int_orders",
            depends_on_nodes=("model.analytics.stg_orders",),
        ),
        build_manifest_model_node(
            unique_id="model.analytics.unrelated",
            package_name="analytics",
            name="unrelated",
            relation_name="analytics.unrelated",
        ),
    )
)
_SQLBUILD_SQL: dict[str, str] = {
    "stg_local": "select 1",
    "fact_orders": 'select * from __dbt_ref("int_orders")',
    "mart_orders": 'select * from __ref("fact_orders")',
    "local_only": 'select * from __ref("stg_local")',
}
_SQLBUILD_TAGS: dict[str, tuple[str, ...]] = {
    "fact_orders": ("nightly",),
    "mart_orders": ("nightly",),
}
_SQLBUILD_PATHS: dict[str, str] = {
    "stg_local": "models/staging/stg_local.sql",
    "fact_orders": "models/marts/fact_orders.sql",
    "mart_orders": "models/marts/mart_orders.sql",
    "local_only": "models/local/local_only.sql",
}


PLAN_ORCHESTRATION_TEST_CASES: list[DbtPlanOrchestrationTestCase] = [
    DbtPlanOrchestrationTestCase(
        description="plans SQLBuild-only selector and skips dbt",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("local_only",),
        exclude=(),
        full_dbt_ls_unique_ids=(),
        anchor_dbt_ls_unique_ids_by_term={},
        expected_dbt_ls_selects=(("local_only",),),
        expected_sqlbuild_model_names=("local_only",),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(("sqb", "run", "--select", "local_only"),),
        expected_dbt_skipped=True,
        expected_sqlbuild_skipped=False,
        dbt_command_args=("--select", "local_only"),
        expected_primary_dbt_command_argv=("dbt", "run", "--select", "local_only"),
    ),
    DbtPlanOrchestrationTestCase(
        description="plans dbt-only selector and skips SQLBuild",
        command="build",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("state:modified",),
        exclude=(),
        full_dbt_ls_unique_ids=("model.analytics.int_orders",),
        anchor_dbt_ls_unique_ids_by_term={},
        expected_dbt_ls_selects=(("state:modified",),),
        expected_sqlbuild_model_names=(),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(),
        expected_dbt_skipped=False,
        expected_sqlbuild_skipped=True,
        dbt_command_args=("--select", "state:modified"),
        expected_primary_dbt_command_argv=("dbt", "build", "--select", "state:modified"),
    ),
    DbtPlanOrchestrationTestCase(
        description="uses only trailing dbt selector anchors for SQLBuild expansion",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("state:modified", "package:stripe+"),
        exclude=(),
        full_dbt_ls_unique_ids=("model.analytics.unrelated", "model.analytics.int_orders"),
        anchor_dbt_ls_unique_ids_by_term={"package:stripe+": ("model.analytics.int_orders",)},
        expected_dbt_ls_selects=(("state:modified", "package:stripe+"), ("package:stripe+",)),
        expected_sqlbuild_model_names=("fact_orders", "mart_orders"),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(("sqb", "run", "--select", "fact_orders", "mart_orders"),),
        expected_dbt_skipped=False,
        expected_sqlbuild_skipped=False,
        dbt_command_args=("--select", "state:modified", "package:stripe+"),
        expected_primary_dbt_command_argv=(
            "dbt",
            "run",
            "--select",
            "state:modified",
            "package:stripe+",
        ),
        expected_dbt_anchor_terms=("package:stripe+",),
    ),
    DbtPlanOrchestrationTestCase(
        description="derives compact dbt boundary selectors for SQLBuild-owned upstreams",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("+fact_orders",),
        exclude=(),
        full_dbt_ls_unique_ids=(),
        anchor_dbt_ls_unique_ids_by_term={},
        expected_dbt_ls_selects=(("+fact_orders",),),
        expected_sqlbuild_model_names=("fact_orders",),
        expected_dbt_required_unique_ids=(
            "model.analytics.int_orders",
            "model.analytics.stg_orders",
        ),
        expected_dbt_required_selector_terms=("+analytics.int_orders",),
        expected_supplemental_dbt_command_argvs=(
            (
                "dbt",
                "run",
                "--project-dir",
                "/repo/dbt",
                "--target",
                "dev",
                "--select",
                "+analytics.int_orders",
            ),
        ),
        expected_sqlbuild_command_argvs=(("sqb", "run", "--select", "fact_orders"),),
        expected_dbt_skipped=False,
        expected_sqlbuild_skipped=False,
        dbt_command_args=("--select", "+fact_orders"),
        expected_primary_dbt_command_argv=("dbt", "run", "--select", "+fact_orders"),
    ),
    DbtPlanOrchestrationTestCase(
        description="does not run anchor ls for SQLBuild-owned trailing plus terms",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("state:modified", "fact_orders+"),
        exclude=(),
        full_dbt_ls_unique_ids=("model.analytics.int_orders",),
        anchor_dbt_ls_unique_ids_by_term={},
        expected_dbt_ls_selects=(("state:modified", "fact_orders+"),),
        expected_sqlbuild_model_names=("fact_orders", "mart_orders"),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(("sqb", "run", "--select", "fact_orders", "mart_orders"),),
        expected_dbt_skipped=False,
        expected_sqlbuild_skipped=False,
        dbt_command_args=("--select", "state:modified", "fact_orders+"),
        expected_primary_dbt_command_argv=(
            "dbt",
            "run",
            "--select",
            "state:modified",
            "fact_orders+",
        ),
    ),
    DbtPlanOrchestrationTestCase(
        description="passes excludes to full and anchor dbt ls and final SQLBuild selection",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("state:modified", "package:stripe+"),
        exclude=("tag:nightly",),
        full_dbt_ls_unique_ids=("model.analytics.int_orders",),
        anchor_dbt_ls_unique_ids_by_term={"package:stripe+": ("model.analytics.int_orders",)},
        expected_dbt_ls_selects=(("state:modified", "package:stripe+"), ("package:stripe+",)),
        expected_dbt_ls_excludes=(("tag:nightly",), ("tag:nightly",)),
        expected_sqlbuild_model_names=(),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(),
        expected_dbt_skipped=False,
        expected_sqlbuild_skipped=True,
        dbt_command_args=(
            "--select",
            "state:modified",
            "package:stripe+",
            "--exclude",
            "tag:nightly",
        ),
        expected_primary_dbt_command_argv=(
            "dbt",
            "run",
            "--select",
            "state:modified",
            "package:stripe+",
            "--exclude",
            "tag:nightly",
        ),
        expected_dbt_anchor_terms=("package:stripe+",),
    ),
    DbtPlanOrchestrationTestCase(
        description="preserves path translation metadata through orchestration",
        command="plan",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("path:models/marts",),
        exclude=(),
        full_dbt_ls_unique_ids=(),
        anchor_dbt_ls_unique_ids_by_term={},
        expected_dbt_ls_selects=(("path:models/marts",),),
        expected_sqlbuild_model_names=("fact_orders", "mart_orders"),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(
            ("sqb", "plan", "--select", "fact_orders", "mart_orders"),
        ),
        expected_dbt_skipped=True,
        expected_sqlbuild_skipped=False,
        dbt_command_args=("--select", "path:models/marts"),
        expected_primary_dbt_command_argv=("dbt", "plan", "--select", "path:models/marts"),
        expected_path_translations=(("path:models/marts", "path:marts"),),
    ),
    DbtPlanOrchestrationTestCase(
        description="does not run anchor ls for SQLBuild-owned path in mixed selectors",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("state:modified", "path:models/marts+"),
        exclude=(),
        full_dbt_ls_unique_ids=("model.analytics.int_orders",),
        anchor_dbt_ls_unique_ids_by_term={},
        expected_dbt_ls_selects=(("state:modified", "path:models/marts+"),),
        expected_sqlbuild_model_names=("fact_orders", "mart_orders"),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(("sqb", "run", "--select", "fact_orders", "mart_orders"),),
        expected_dbt_skipped=False,
        expected_sqlbuild_skipped=False,
        dbt_command_args=("--select", "state:modified", "path:models/marts+"),
        expected_primary_dbt_command_argv=(
            "dbt",
            "run",
            "--select",
            "state:modified",
            "path:models/marts+",
        ),
        expected_path_translations=(("path:models/marts+", "path:marts"),),
    ),
    DbtPlanOrchestrationTestCase(
        description="passes SQLBuild routed args after selected models",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("local_only",),
        exclude=(),
        full_dbt_ls_unique_ids=(),
        anchor_dbt_ls_unique_ids_by_term={},
        expected_dbt_ls_selects=(("local_only",),),
        expected_sqlbuild_model_names=("local_only",),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(
            ("sqb", "run", "--select", "local_only", "--start-cursor-int", "10"),
        ),
        expected_dbt_skipped=True,
        expected_sqlbuild_skipped=False,
        dbt_command_args=("--select", "local_only"),
        sqlbuild_command_args=("--start-cursor-int", "10"),
        expected_primary_dbt_command_argv=("dbt", "run", "--select", "local_only"),
    ),
    DbtPlanOrchestrationTestCase(
        description="treats SQLBuild-owned tag trailing plus as direct SQLBuild work",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("tag:nightly+",),
        exclude=(),
        full_dbt_ls_unique_ids=(),
        anchor_dbt_ls_unique_ids_by_term={},
        expected_dbt_ls_selects=(("tag:nightly+",),),
        expected_sqlbuild_model_names=("fact_orders", "mart_orders"),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(("sqb", "run", "--select", "fact_orders", "mart_orders"),),
        expected_dbt_skipped=True,
        expected_sqlbuild_skipped=False,
        dbt_command_args=("--select", "tag:nightly+"),
        expected_primary_dbt_command_argv=("dbt", "run", "--select", "tag:nightly+"),
    ),
    DbtPlanOrchestrationTestCase(
        description="does not run anchor ls for SQLBuild-owned tag in mixed selectors",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("state:modified", "tag:nightly+"),
        exclude=(),
        full_dbt_ls_unique_ids=("model.analytics.int_orders",),
        anchor_dbt_ls_unique_ids_by_term={},
        expected_dbt_ls_selects=(("state:modified", "tag:nightly+"),),
        expected_sqlbuild_model_names=("fact_orders", "mart_orders"),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(("sqb", "run", "--select", "fact_orders", "mart_orders"),),
        expected_dbt_skipped=False,
        expected_sqlbuild_skipped=False,
        dbt_command_args=("--select", "state:modified", "tag:nightly+"),
        expected_primary_dbt_command_argv=(
            "dbt",
            "run",
            "--select",
            "state:modified",
            "tag:nightly+",
        ),
    ),
    DbtPlanOrchestrationTestCase(
        description="treats dbt-owned tag trailing plus as anchor when no SQLBuild tag matches",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("tag:dbt_only+",),
        exclude=(),
        full_dbt_ls_unique_ids=("model.analytics.int_orders",),
        anchor_dbt_ls_unique_ids_by_term={"tag:dbt_only+": ("model.analytics.int_orders",)},
        expected_dbt_ls_selects=(("tag:dbt_only+",),),
        expected_sqlbuild_model_names=("fact_orders", "mart_orders"),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(("sqb", "run", "--select", "fact_orders", "mart_orders"),),
        expected_dbt_skipped=False,
        expected_sqlbuild_skipped=False,
        dbt_command_args=("--select", "tag:dbt_only+"),
        expected_primary_dbt_command_argv=("dbt", "run", "--select", "tag:dbt_only+"),
        expected_dbt_anchor_terms=("tag:dbt_only+",),
    ),
    DbtPlanOrchestrationTestCase(
        description="treats comma expression as one memoized dbt anchor term",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("state:modified,tag:daily+",),
        exclude=(),
        full_dbt_ls_unique_ids=("model.analytics.int_orders",),
        anchor_dbt_ls_unique_ids_by_term={
            "state:modified,tag:daily+": ("model.analytics.int_orders",)
        },
        expected_dbt_ls_selects=(("state:modified,tag:daily+",),),
        expected_sqlbuild_model_names=("fact_orders", "mart_orders"),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(("sqb", "run", "--select", "fact_orders", "mart_orders"),),
        expected_dbt_skipped=False,
        expected_sqlbuild_skipped=False,
        dbt_command_args=("--select", "state:modified,tag:daily+"),
        expected_primary_dbt_command_argv=(
            "dbt",
            "run",
            "--select",
            "state:modified,tag:daily+",
        ),
        expected_dbt_anchor_terms=("state:modified,tag:daily+",),
    ),
    DbtPlanOrchestrationTestCase(
        description="keeps empty anchor terms without adding SQLBuild work",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("state:modified", "package:stripe+"),
        exclude=(),
        full_dbt_ls_unique_ids=("model.analytics.unrelated",),
        anchor_dbt_ls_unique_ids_by_term={"package:stripe+": ()},
        expected_dbt_ls_selects=(("state:modified", "package:stripe+"), ("package:stripe+",)),
        expected_sqlbuild_model_names=(),
        expected_dbt_required_unique_ids=(),
        expected_dbt_required_selector_terms=(),
        expected_supplemental_dbt_command_argvs=(),
        expected_sqlbuild_command_argvs=(),
        expected_dbt_skipped=False,
        expected_sqlbuild_skipped=True,
        dbt_command_args=("--select", "state:modified", "package:stripe+"),
        expected_primary_dbt_command_argv=(
            "dbt",
            "run",
            "--select",
            "state:modified",
            "package:stripe+",
        ),
        expected_dbt_anchor_terms=("package:stripe+",),
    ),
    DbtPlanOrchestrationTestCase(
        description="includes all dbt options in supplemental boundary commands",
        command="run",
        manifest_data=_MANIFEST_DATA,
        sqlbuild_model_sql_by_name=_SQLBUILD_SQL,
        sqlbuild_model_tags_by_name=_SQLBUILD_TAGS,
        sqlbuild_model_path_by_name=_SQLBUILD_PATHS,
        select=("+fact_orders",),
        exclude=(),
        full_dbt_ls_unique_ids=(),
        anchor_dbt_ls_unique_ids_by_term={},
        expected_dbt_ls_selects=(("+fact_orders",),),
        expected_sqlbuild_model_names=("fact_orders",),
        expected_dbt_required_unique_ids=(
            "model.analytics.int_orders",
            "model.analytics.stg_orders",
        ),
        expected_dbt_required_selector_terms=("+analytics.int_orders",),
        expected_supplemental_dbt_command_argvs=(
            (
                "dbt",
                "run",
                "--project-dir",
                "/repo/dbt",
                "--profiles-dir",
                "/repo/profiles",
                "--target",
                "prod",
                "--target-path",
                "/repo/dbt-target",
                "--vars",
                '{"run_date":"2026-01-01"}',
                "--state",
                "/repo/state",
                "--defer",
                "--select",
                "+analytics.int_orders",
            ),
        ),
        expected_sqlbuild_command_argvs=(("sqb", "run", "--select", "fact_orders"),),
        expected_dbt_skipped=False,
        expected_sqlbuild_skipped=False,
        dbt_options=_FULL_DBT_OPTIONS,
        dbt_command_args=("--select", "+fact_orders"),
        expected_primary_dbt_command_argv=("dbt", "run", "--select", "+fact_orders"),
    ),
]


@pytest.mark.parametrize(
    "test_case",
    PLAN_ORCHESTRATION_TEST_CASES,
    ids=[case.description for case in PLAN_ORCHESTRATION_TEST_CASES],
)
def test_given_dbt_interop_inputs_when_planning_then_returns_expected_plan(
    test_case: DbtPlanOrchestrationTestCase,
) -> None:
    manifest: DbtManifestIndex = build_dbt_manifest_index(raw_data=test_case.manifest_data)
    project: CompiledProject = build_compiled_project_with_model_specs(
        sql_by_model_name=test_case.sqlbuild_model_sql_by_name,
        tags_by_model_name=test_case.sqlbuild_model_tags_by_name,
        path_by_model_name=test_case.sqlbuild_model_path_by_name,
    )
    graph: DbtCombinedGraph = build_dbt_combined_graph(manifest=manifest, project=project)
    dbt_options: DbtCliOptions = test_case.dbt_options or _DBT_OPTIONS
    invoker: MappingDbtInvoker = build_dbt_plan_mapping_invoker(
        options=dbt_options,
        select=test_case.select,
        exclude=test_case.exclude,
        full_dbt_ls_unique_ids=test_case.full_dbt_ls_unique_ids,
        anchor_dbt_ls_unique_ids_by_term=test_case.anchor_dbt_ls_unique_ids_by_term,
    )
    runner: DbtRunner = DbtRunner(invoker=invoker)

    plan: DbtInteropPlan = plan_dbt_interop_command(
        command=test_case.command,
        project=project,
        manifest=manifest,
        graph=graph,
        dbt_runner=runner,
        dbt_options=dbt_options,
        select=test_case.select,
        exclude=test_case.exclude,
        dbt_command_args=test_case.dbt_command_args,
        sqlbuild_command_args=test_case.sqlbuild_command_args,
    )

    assert tuple(extract_dbt_ls_selects(call[0]) for call in invoker.calls) == (
        test_case.expected_dbt_ls_selects
    )
    expected_excludes: tuple[tuple[str, ...], ...] = test_case.expected_dbt_ls_excludes or tuple(
        () for _call in invoker.calls
    )
    assert tuple(extract_dbt_ls_excludes(call[0]) for call in invoker.calls) == expected_excludes
    assert plan.dbt_command_argv == test_case.expected_primary_dbt_command_argv
    assert plan.selection.sqlbuild_model_names == test_case.expected_sqlbuild_model_names
    assert plan.selection.dbt_required_unique_ids == test_case.expected_dbt_required_unique_ids
    assert plan.selection.dbt_anchor_terms == test_case.expected_dbt_anchor_terms
    assert plan.selection.path_translations == test_case.expected_path_translations
    assert plan.dbt_required_selector_terms == test_case.expected_dbt_required_selector_terms
    assert plan.supplemental_dbt_command_argvs == (
        test_case.expected_supplemental_dbt_command_argvs
    )
    assert plan.sqlbuild_command_argvs == test_case.expected_sqlbuild_command_argvs
    assert (plan.dbt_skip_reason is not None) == test_case.expected_dbt_skipped
    assert (plan.sqlbuild_skip_reason is not None) == test_case.expected_sqlbuild_skipped
