from __future__ import annotations

import pytest

from sqlbuild.integrations.dbt.exceptions import DbtInteropArgumentError
from sqlbuild.integrations.dbt.helpers.args import route_dbt_interop_args
from sqlbuild.integrations.dbt.models import DbtInteropRoutedArgs
from tests.unit.src.sqlbuild.integrations.dbt._test_types import (
    DbtArgRoutingErrorTestCase,
    DbtArgRoutingTestCase,
)

ROUTING_TEST_CASES: list[DbtArgRoutingTestCase] = [
    DbtArgRoutingTestCase(
        description="routes select and exclude only to dbt and combined selection",
        command="run",
        args=("--select", "fact_orders", "tag:daily+", "--exclude", "tag:deprecated"),
        expected_select=("fact_orders", "tag:daily+"),
        expected_exclude=("tag:deprecated",),
        expected_dbt_args=(
            "--select",
            "fact_orders",
            "tag:daily+",
            "--exclude",
            "tag:deprecated",
        ),
        expected_sqlbuild_args=(),
    ),
    DbtArgRoutingTestCase(
        description="preserves repeated select flags and short select alias",
        command="build",
        args=("-s", "stg_orders", "--select", "fact_orders+", "--exclude", "tag:old"),
        expected_select=("stg_orders", "fact_orders+"),
        expected_exclude=("tag:old",),
        expected_dbt_args=(
            "-s",
            "stg_orders",
            "--select",
            "fact_orders+",
            "--exclude",
            "tag:old",
        ),
        expected_sqlbuild_args=(),
    ),
    DbtArgRoutingTestCase(
        description="routes shared vars full refresh threads and event time to both sides",
        command="run",
        args=(
            "--vars",
            '{"run_date":"2026-01-01"}',
            "--full-refresh",
            "--threads",
            "8",
            "--event-time-start",
            "2024-09-01",
            "--event-time-end",
            "2024-09-04",
        ),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(
            "--vars",
            '{"run_date":"2026-01-01"}',
            "--full-refresh",
            "--threads",
            "8",
            "--event-time-start",
            "2024-09-01",
            "--event-time-end",
            "2024-09-04",
        ),
        expected_sqlbuild_args=(
            "--vars",
            '{"run_date":"2026-01-01"}',
            "--full-refresh",
            "--concurrency",
            "8",
            "--start-cursor-ts",
            "2024-09-01",
            "--end-cursor-ts",
            "2024-09-04",
        ),
    ),
    DbtArgRoutingTestCase(
        description="routes shared vars full refresh and threads for build",
        command="build",
        args=("--vars", '{"batch":"daily"}', "--full-refresh", "--threads", "4"),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=("--vars", '{"batch":"daily"}', "--full-refresh", "--threads", "4"),
        expected_sqlbuild_args=(
            "--vars",
            '{"batch":"daily"}',
            "--full-refresh",
            "--concurrency",
            "4",
        ),
    ),
    DbtArgRoutingTestCase(
        description="passes full refresh to dbt only for test",
        command="test",
        args=("--full-refresh",),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=("--full-refresh",),
        expected_sqlbuild_args=(),
    ),
    DbtArgRoutingTestCase(
        description="passes event time to dbt only for test",
        command="test",
        args=(
            "--event-time-start",
            "2024-09-01",
            "--event-time-end",
            "2024-09-04",
        ),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(
            "--event-time-start",
            "2024-09-01",
            "--event-time-end",
            "2024-09-04",
        ),
        expected_sqlbuild_args=(),
    ),
    DbtArgRoutingTestCase(
        description="passes vars and threads to both sides for test",
        command="test",
        args=("--vars", '{"suite":"nightly"}', "--threads", "3"),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=("--vars", '{"suite":"nightly"}', "--threads", "3"),
        expected_sqlbuild_args=("--vars", '{"suite":"nightly"}', "--concurrency", "3"),
    ),
    DbtArgRoutingTestCase(
        description="routes dbt project runtime flags only to dbt",
        command="build",
        args=(
            "--project-dir",
            "dbt",
            "--profiles-dir",
            "profiles",
            "--profile",
            "analytics",
            "--target",
            "prod",
            "--target-path",
            "target/dbt",
            "--state",
            "state",
            "--defer",
            "--indirect-selection",
            "eager",
        ),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(
            "--project-dir",
            "dbt",
            "--profiles-dir",
            "profiles",
            "--profile",
            "analytics",
            "--target",
            "prod",
            "--target-path",
            "target/dbt",
            "--state",
            "state",
            "--defer",
            "--indirect-selection",
            "eager",
        ),
        expected_sqlbuild_args=(),
    ),
    DbtArgRoutingTestCase(
        description="routes SQLBuild cursor and defer overrides to SQLBuild only",
        command="run",
        args=(
            "--sqb-start-cursor-int",
            "100",
            "--sqb-end-cursor-int",
            "200",
            "--sqb-defer-to",
            "prod",
        ),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(),
        expected_sqlbuild_args=(
            "--start-cursor-int",
            "100",
            "--end-cursor-int",
            "200",
            "--defer-to",
            "prod",
        ),
    ),
    DbtArgRoutingTestCase(
        description="routes SQLBuild timestamp cursor overrides for plan",
        command="plan",
        args=(
            "--sqb-start-cursor-ts",
            "2024-01-01",
            "--sqb-end-cursor-ts",
            "2024-01-02",
        ),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(),
        expected_sqlbuild_args=(
            "--start-cursor-ts",
            "2024-01-01",
            "--end-cursor-ts",
            "2024-01-02",
        ),
    ),
    DbtArgRoutingTestCase(
        description="routes SQLBuild timestamp cursor overrides for run",
        command="run",
        args=(
            "--sqb-start-cursor-ts",
            "2024-01-01",
            "--sqb-end-cursor-ts",
            "2024-01-02",
        ),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(),
        expected_sqlbuild_args=(
            "--start-cursor-ts",
            "2024-01-01",
            "--end-cursor-ts",
            "2024-01-02",
        ),
    ),
    DbtArgRoutingTestCase(
        description="routes SQLBuild timestamp cursor overrides for build",
        command="build",
        args=(
            "--sqb-start-cursor-ts",
            "2024-01-01",
            "--sqb-end-cursor-ts",
            "2024-01-02",
        ),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(),
        expected_sqlbuild_args=(
            "--start-cursor-ts",
            "2024-01-01",
            "--end-cursor-ts",
            "2024-01-02",
        ),
    ),
    DbtArgRoutingTestCase(
        description="routes SQLBuild integer cursor overrides for plan",
        command="plan",
        args=("--sqb-start-cursor-int", "10", "--sqb-end-cursor-int", "20"),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(),
        expected_sqlbuild_args=("--start-cursor-int", "10", "--end-cursor-int", "20"),
    ),
    DbtArgRoutingTestCase(
        description="routes SQLBuild integer cursor overrides for build",
        command="build",
        args=("--sqb-start-cursor-int", "10", "--sqb-end-cursor-int", "20"),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(),
        expected_sqlbuild_args=("--start-cursor-int", "10", "--end-cursor-int", "20"),
    ),
    DbtArgRoutingTestCase(
        description="routes SQLBuild defer override for plan",
        command="plan",
        args=("--sqb-defer-to", "prod"),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(),
        expected_sqlbuild_args=("--defer-to", "prod"),
    ),
    DbtArgRoutingTestCase(
        description="routes SQLBuild defer override for build",
        command="build",
        args=("--sqb-defer-to", "prod"),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(),
        expected_sqlbuild_args=("--defer-to", "prod"),
    ),
    DbtArgRoutingTestCase(
        description="routes SQLBuild execution bool flags for run",
        command="run",
        args=("--sqb-fail-fast", "--sqb-verbose"),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(),
        expected_sqlbuild_args=("--fail-fast", "--verbose"),
    ),
    DbtArgRoutingTestCase(
        description="routes SQLBuild execution bool flags for build",
        command="build",
        args=("--sqb-fail-fast", "--sqb-verbose"),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(),
        expected_sqlbuild_args=("--fail-fast", "--verbose"),
    ),
    DbtArgRoutingTestCase(
        description="passes unknown dbt-native flags through to dbt",
        command="test",
        args=("--store-failures", "--favor-state"),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=("--store-failures", "--favor-state"),
        expected_sqlbuild_args=(),
    ),
    DbtArgRoutingTestCase(
        description="passes unknown dbt-native flag values through as dbt tokens",
        command="run",
        args=("--log-level", "debug"),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=("--log-level", "debug"),
        expected_sqlbuild_args=(),
    ),
    DbtArgRoutingTestCase(
        description="routes event time with SQLBuild integer cursors without conflict",
        command="run",
        args=(
            "--event-time-start",
            "2024-09-01",
            "--event-time-end",
            "2024-09-04",
            "--sqb-start-cursor-int",
            "10",
            "--sqb-end-cursor-int",
            "20",
        ),
        expected_select=(),
        expected_exclude=(),
        expected_dbt_args=(
            "--event-time-start",
            "2024-09-01",
            "--event-time-end",
            "2024-09-04",
        ),
        expected_sqlbuild_args=(
            "--start-cursor-ts",
            "2024-09-01",
            "--end-cursor-ts",
            "2024-09-04",
            "--start-cursor-int",
            "10",
            "--end-cursor-int",
            "20",
        ),
    ),
]

ERROR_TEST_CASES: list[DbtArgRoutingErrorTestCase] = [
    DbtArgRoutingErrorTestCase(
        description="rejects denylisted select",
        command="run",
        args=("--sqb-select", "value"),
        expected_error_fragment="is not allowed for sqb dbt commands",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects denylisted exclude",
        command="run",
        args=("--sqb-exclude", "value"),
        expected_error_fragment="is not allowed for sqb dbt commands",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects denylisted project dir",
        command="run",
        args=("--sqb-project-dir", "value"),
        expected_error_fragment="is not allowed for sqb dbt commands",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects denylisted vars",
        command="run",
        args=("--sqb-vars", "value"),
        expected_error_fragment="is not allowed for sqb dbt commands",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects denylisted full refresh",
        command="run",
        args=("--sqb-full-refresh", "value"),
        expected_error_fragment="is not allowed for sqb dbt commands",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects denylisted concurrency",
        command="run",
        args=("--sqb-concurrency", "value"),
        expected_error_fragment="is not allowed for sqb dbt commands",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects denylisted threads",
        command="run",
        args=("--sqb-threads", "value"),
        expected_error_fragment="is not allowed for sqb dbt commands",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects event time start without end",
        command="run",
        args=("--event-time-start", "2024-09-01"),
        expected_error_fragment="must be provided together",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects event time end without start",
        command="run",
        args=("--event-time-end", "2024-09-04"),
        expected_error_fragment="must be provided together",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects event time with SQLBuild timestamp cursor",
        command="run",
        args=(
            "--event-time-start",
            "2024-09-01",
            "--event-time-end",
            "2024-09-04",
            "--sqb-start-cursor-ts",
            "2024-09-02",
        ),
        expected_error_fragment="conflict with --sqb-start-cursor-ts/end-cursor-ts",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects event time with SQLBuild end timestamp cursor",
        command="run",
        args=(
            "--event-time-start",
            "2024-09-01",
            "--event-time-end",
            "2024-09-04",
            "--sqb-end-cursor-ts",
            "2024-09-05",
        ),
        expected_error_fragment="conflict with --sqb-start-cursor-ts/end-cursor-ts",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects invalid stripped SQLBuild option",
        command="run",
        args=("--sqb-not-real", "value"),
        expected_error_fragment="is not a valid SQLBuild option",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects unsupported SQLBuild hard copy option on run",
        command="run",
        args=("--sqb-hard-copy",),
        expected_error_fragment="is not a valid SQLBuild option",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects run-only SQLBuild execution flag on plan",
        command="plan",
        args=("--sqb-fail-fast",),
        expected_error_fragment="is not a valid SQLBuild option",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects run cursor option on test",
        command="test",
        args=("--sqb-start-cursor-int", "1"),
        expected_error_fragment="is not a valid SQLBuild option",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects missing value for dbt flag",
        command="run",
        args=("--target",),
        expected_error_fragment="requires a value",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects missing value for SQLBuild flag",
        command="run",
        args=("--sqb-defer-to",),
        expected_error_fragment="requires a value",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects missing value for select",
        command="run",
        args=("--select",),
        expected_error_fragment="requires at least one value",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects missing value for exclude",
        command="run",
        args=("--exclude",),
        expected_error_fragment="requires at least one value",
    ),
    DbtArgRoutingErrorTestCase(
        description="rejects unsupported dbt interop command",
        command="clone",
        args=(),
        expected_error_fragment="clone",
    ),
]


@pytest.mark.parametrize(
    "test_case",
    ROUTING_TEST_CASES,
    ids=[case.description for case in ROUTING_TEST_CASES],
)
def test_given_dbt_interop_args_when_routing_then_returns_expected_buckets(
    test_case: DbtArgRoutingTestCase,
) -> None:
    result: DbtInteropRoutedArgs = route_dbt_interop_args(
        command=test_case.command,
        args=test_case.args,
    )

    assert result.command == test_case.command
    assert result.select == test_case.expected_select
    assert result.exclude == test_case.expected_exclude
    assert result.dbt_args == test_case.expected_dbt_args
    assert result.sqlbuild_args == test_case.expected_sqlbuild_args


@pytest.mark.parametrize(
    "test_case",
    ERROR_TEST_CASES,
    ids=[case.description for case in ERROR_TEST_CASES],
)
def test_given_invalid_dbt_interop_args_when_routing_then_raises_clear_error(
    test_case: DbtArgRoutingErrorTestCase,
) -> None:
    with pytest.raises(DbtInteropArgumentError, match=test_case.expected_error_fragment):
        route_dbt_interop_args(command=test_case.command, args=test_case.args)
