from __future__ import annotations

import duckdb
import pytest

from sqlbuild.executor.scenario._helpers.capture.columns import local_type_for_warehouse_type
from tests.unit.src.sqlbuild.executor.scenario._helpers._test_types import (
    ScenarioSnapshotLocalTypeMappingTestCase,
)


@pytest.mark.parametrize(
    "test_case",
    [
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake number preserves default integer precision",
            sql_analysis_dialect="snowflake",
            warehouse_type="NUMBER",
            expected_local_type="DECIMAL(38, 0)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake number preserves explicit precision and scale",
            sql_analysis_dialect="snowflake",
            warehouse_type="NUMBER(10,2)",
            expected_local_type="DECIMAL(10, 2)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake decimal preserves explicit precision and scale",
            sql_analysis_dialect="snowflake",
            warehouse_type="DECIMAL(12,4)",
            expected_local_type="DECIMAL(12, 4)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake numeric preserves explicit integer scale",
            sql_analysis_dialect="snowflake",
            warehouse_type="NUMERIC(9,0)",
            expected_local_type="DECIMAL(9, 0)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake int maps to int",
            sql_analysis_dialect="snowflake",
            warehouse_type="INT",
            expected_local_type="INT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake bigint maps to bigint",
            sql_analysis_dialect="snowflake",
            warehouse_type="BIGINT",
            expected_local_type="BIGINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake boolean maps to boolean",
            sql_analysis_dialect="snowflake",
            warehouse_type="BOOLEAN",
            expected_local_type="BOOLEAN",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake float preserves double precision",
            sql_analysis_dialect="snowflake",
            warehouse_type="FLOAT",
            expected_local_type="DOUBLE",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake float4 remains real",
            sql_analysis_dialect="snowflake",
            warehouse_type="FLOAT4",
            expected_local_type="REAL",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake float8 maps to double",
            sql_analysis_dialect="snowflake",
            warehouse_type="FLOAT8",
            expected_local_type="DOUBLE",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake real remains real",
            sql_analysis_dialect="snowflake",
            warehouse_type="REAL",
            expected_local_type="REAL",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake varchar maps through sql_analysis text",
            sql_analysis_dialect="snowflake",
            warehouse_type="VARCHAR",
            expected_local_type="TEXT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake varchar length is preserved",
            sql_analysis_dialect="snowflake",
            warehouse_type="VARCHAR(255)",
            expected_local_type="TEXT(255)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake string maps to text",
            sql_analysis_dialect="snowflake",
            warehouse_type="STRING",
            expected_local_type="TEXT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake binary falls back to varchar for jsonl replay",
            sql_analysis_dialect="snowflake",
            warehouse_type="BINARY",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake date maps to date",
            sql_analysis_dialect="snowflake",
            warehouse_type="DATE",
            expected_local_type="DATE",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake time maps to time",
            sql_analysis_dialect="snowflake",
            warehouse_type="TIME",
            expected_local_type="TIME",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake timestamp ntz maps to timestamp",
            sql_analysis_dialect="snowflake",
            warehouse_type="TIMESTAMP_NTZ",
            expected_local_type="TIMESTAMP",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake timestamp ltz maps to timestamptz",
            sql_analysis_dialect="snowflake",
            warehouse_type="TIMESTAMP_LTZ",
            expected_local_type="TIMESTAMPTZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake timestamp ltz precision drops unsupported timestamptz parameter",
            sql_analysis_dialect="snowflake",
            warehouse_type="TIMESTAMP_LTZ(9)",
            expected_local_type="TIMESTAMPTZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake timestamp ntz precision is preserved",
            sql_analysis_dialect="snowflake",
            warehouse_type="TIMESTAMP_NTZ(9)",
            expected_local_type="TIMESTAMP(9)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake timestamp with timezone maps to timestamptz",
            sql_analysis_dialect="snowflake",
            warehouse_type="TIMESTAMP_TZ",
            expected_local_type="TIMESTAMPTZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake object falls back to json",
            sql_analysis_dialect="snowflake",
            warehouse_type="OBJECT",
            expected_local_type="JSON",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake bare array falls back to json",
            sql_analysis_dialect="snowflake",
            warehouse_type="ARRAY",
            expected_local_type="JSON",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake variant remains variant",
            sql_analysis_dialect="snowflake",
            warehouse_type="VARIANT",
            expected_local_type="VARIANT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake geography falls back to varchar",
            sql_analysis_dialect="snowflake",
            warehouse_type="GEOGRAPHY",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake geometry falls back to varchar for jsonl replay",
            sql_analysis_dialect="snowflake",
            warehouse_type="GEOMETRY",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake vector falls back to json",
            sql_analysis_dialect="snowflake",
            warehouse_type="VECTOR(FLOAT, 3)",
            expected_local_type="JSON",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery int64 maps to bigint",
            sql_analysis_dialect="bigquery",
            warehouse_type="INT64",
            expected_local_type="BIGINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery integer maps to int",
            sql_analysis_dialect="bigquery",
            warehouse_type="INTEGER",
            expected_local_type="INT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery boolean maps to boolean",
            sql_analysis_dialect="bigquery",
            warehouse_type="BOOL",
            expected_local_type="BOOLEAN",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery float64 maps to double",
            sql_analysis_dialect="bigquery",
            warehouse_type="FLOAT64",
            expected_local_type="DOUBLE",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery numeric maps to decimal",
            sql_analysis_dialect="bigquery",
            warehouse_type="NUMERIC",
            expected_local_type="DECIMAL",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery numeric explicit precision and scale are preserved",
            sql_analysis_dialect="bigquery",
            warehouse_type="NUMERIC(10,2)",
            expected_local_type="DECIMAL(10, 2)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery bignumeric default maps to wide decimal",
            sql_analysis_dialect="bigquery",
            warehouse_type="BIGNUMERIC",
            expected_local_type="DECIMAL(38, 5)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery bignumeric explicit scale avoids malformed sql_analysis rendering",
            sql_analysis_dialect="bigquery",
            warehouse_type="BIGNUMERIC(38,9)",
            expected_local_type="DECIMAL(38, 9)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery date range falls back to varchar",
            sql_analysis_dialect="bigquery",
            warehouse_type="RANGE<DATE>",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery datetime range falls back to varchar",
            sql_analysis_dialect="bigquery",
            warehouse_type="RANGE<DATETIME>",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery timestamp range falls back to varchar",
            sql_analysis_dialect="bigquery",
            warehouse_type="RANGE<TIMESTAMP>",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery array maps to duckdb list type",
            sql_analysis_dialect="bigquery",
            warehouse_type="ARRAY<INT64>",
            expected_local_type="BIGINT[]",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery string maps to text",
            sql_analysis_dialect="bigquery",
            warehouse_type="STRING",
            expected_local_type="TEXT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery bytes falls back to varchar for jsonl replay",
            sql_analysis_dialect="bigquery",
            warehouse_type="BYTES",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery parameterized bytes falls back to varchar for jsonl replay",
            sql_analysis_dialect="bigquery",
            warehouse_type="BYTES(10)",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery json maps to json",
            sql_analysis_dialect="bigquery",
            warehouse_type="JSON",
            expected_local_type="JSON",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery date maps to date",
            sql_analysis_dialect="bigquery",
            warehouse_type="DATE",
            expected_local_type="DATE",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery datetime maps to timestamp",
            sql_analysis_dialect="bigquery",
            warehouse_type="DATETIME",
            expected_local_type="TIMESTAMP",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery timestamp maps to timestamptz",
            sql_analysis_dialect="bigquery",
            warehouse_type="TIMESTAMP",
            expected_local_type="TIMESTAMPTZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery struct maps to duckdb struct type",
            sql_analysis_dialect="bigquery",
            warehouse_type="STRUCT<a INT64>",
            expected_local_type="STRUCT(a BIGINT)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery nested array of struct maps to duckdb list of struct",
            sql_analysis_dialect="bigquery",
            warehouse_type="ARRAY<STRUCT<a INT64, b STRING>>",
            expected_local_type="STRUCT(a BIGINT, b TEXT)[]",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery geography falls back to varchar",
            sql_analysis_dialect="bigquery",
            warehouse_type="GEOGRAPHY",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres smallint maps to smallint",
            sql_analysis_dialect="postgres",
            warehouse_type="smallint",
            expected_local_type="SMALLINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres integer maps to int",
            sql_analysis_dialect="postgres",
            warehouse_type="integer",
            expected_local_type="INT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres bigint maps to bigint",
            sql_analysis_dialect="postgres",
            warehouse_type="bigint",
            expected_local_type="BIGINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres real remains real",
            sql_analysis_dialect="postgres",
            warehouse_type="real",
            expected_local_type="REAL",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres double precision maps to double",
            sql_analysis_dialect="postgres",
            warehouse_type="double precision",
            expected_local_type="DOUBLE",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres numeric maps to decimal",
            sql_analysis_dialect="postgres",
            warehouse_type="numeric",
            expected_local_type="DECIMAL",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres numeric precision and scale are preserved",
            sql_analysis_dialect="postgres",
            warehouse_type="numeric(10,2)",
            expected_local_type="DECIMAL(10, 2)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres text maps to text",
            sql_analysis_dialect="postgres",
            warehouse_type="text",
            expected_local_type="TEXT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres varchar length maps to text length",
            sql_analysis_dialect="postgres",
            warehouse_type="varchar(255)",
            expected_local_type="TEXT(255)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres timestamp with time zone maps to timestamptz",
            sql_analysis_dialect="postgres",
            warehouse_type="timestamp with time zone",
            expected_local_type="TIMESTAMPTZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres jsonb maps to json",
            sql_analysis_dialect="postgres",
            warehouse_type="jsonb",
            expected_local_type="JSON",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres bytea falls back to varchar for jsonl replay",
            sql_analysis_dialect="postgres",
            warehouse_type="bytea",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres uuid maps to uuid",
            sql_analysis_dialect="postgres",
            warehouse_type="uuid",
            expected_local_type="UUID",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres inet maps to inet",
            sql_analysis_dialect="postgres",
            warehouse_type="inet",
            expected_local_type="INET",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres interval maps to interval",
            sql_analysis_dialect="postgres",
            warehouse_type="interval",
            expected_local_type="INTERVAL",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres macaddr falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="macaddr",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres macaddr8 falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="macaddr8",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres xml falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="xml",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres integer array maps to int list",
            sql_analysis_dialect="postgres",
            warehouse_type="integer[]",
            expected_local_type="INT[]",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres geography parse failure falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="geography",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres geometry falls back to varchar for jsonl replay",
            sql_analysis_dialect="postgres",
            warehouse_type="geometry",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres money falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="money",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres serial maps to int",
            sql_analysis_dialect="postgres",
            warehouse_type="serial",
            expected_local_type="INT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres bigserial maps to bigint",
            sql_analysis_dialect="postgres",
            warehouse_type="bigserial",
            expected_local_type="BIGINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres smallserial maps to smallint",
            sql_analysis_dialect="postgres",
            warehouse_type="smallserial",
            expected_local_type="SMALLINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres int4range falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="int4range",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres tstzrange falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="tstzrange",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres name falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="name",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres regclass falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="regclass",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres point falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="point",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres cidr parse failure falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="cidr",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks map maps to duckdb map type",
            sql_analysis_dialect="databricks",
            warehouse_type="MAP<STRING, INT>",
            expected_local_type="MAP(TEXT, INT)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks tinyint maps to tinyint",
            sql_analysis_dialect="databricks",
            warehouse_type="TINYINT",
            expected_local_type="TINYINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks decimal precision and scale are preserved",
            sql_analysis_dialect="databricks",
            warehouse_type="DECIMAL(10,2)",
            expected_local_type="DECIMAL(10, 2)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks string maps to text",
            sql_analysis_dialect="databricks",
            warehouse_type="STRING",
            expected_local_type="TEXT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks varchar length maps to text length",
            sql_analysis_dialect="databricks",
            warehouse_type="VARCHAR(20)",
            expected_local_type="TEXT(20)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks timestamp maps to timestamptz",
            sql_analysis_dialect="databricks",
            warehouse_type="TIMESTAMP",
            expected_local_type="TIMESTAMPTZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks timestamp ntz maps to timestamp",
            sql_analysis_dialect="databricks",
            warehouse_type="TIMESTAMP_NTZ",
            expected_local_type="TIMESTAMP",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks array maps to duckdb list type",
            sql_analysis_dialect="databricks",
            warehouse_type="ARRAY<INT>",
            expected_local_type="INT[]",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks struct maps to duckdb struct type",
            sql_analysis_dialect="databricks",
            warehouse_type="STRUCT<a: INT>",
            expected_local_type="STRUCT(a INT)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks variant is preserved when duckdb supports it",
            sql_analysis_dialect="databricks",
            warehouse_type="VARIANT",
            expected_local_type="VARIANT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks void falls back to varchar",
            sql_analysis_dialect="databricks",
            warehouse_type="VOID",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks nested map of arrays maps to duckdb map",
            sql_analysis_dialect="databricks",
            warehouse_type="MAP<STRING, ARRAY<INT>>",
            expected_local_type="MAP(TEXT, INT[])",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks interval year is preserved",
            sql_analysis_dialect="databricks",
            warehouse_type="INTERVAL YEAR",
            expected_local_type="INTERVAL YEAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks geography parse failure falls back to varchar",
            sql_analysis_dialect="databricks",
            warehouse_type="GEOGRAPHY",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks geometry falls back to varchar for jsonl replay",
            sql_analysis_dialect="databricks",
            warehouse_type="GEOMETRY",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb hugeint maps to duckdb int128 alias",
            sql_analysis_dialect="duckdb",
            warehouse_type="HUGEINT",
            expected_local_type="INT128",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb unsigned integer is preserved",
            sql_analysis_dialect="duckdb",
            warehouse_type="UINTEGER",
            expected_local_type="UINTEGER",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb unsigned hugeint maps to uint128 alias",
            sql_analysis_dialect="duckdb",
            warehouse_type="UHUGEINT",
            expected_local_type="UINT128",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb timestamp ns is preserved",
            sql_analysis_dialect="duckdb",
            warehouse_type="TIMESTAMP_NS",
            expected_local_type="TIMESTAMP_NS",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb blob falls back to varchar for jsonl replay",
            sql_analysis_dialect="duckdb",
            warehouse_type="BLOB",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb struct is preserved with normalized inner type",
            sql_analysis_dialect="duckdb",
            warehouse_type="STRUCT(a INTEGER)",
            expected_local_type="STRUCT(a INT)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb union is preserved with normalized inner types",
            sql_analysis_dialect="duckdb",
            warehouse_type="UNION(num INTEGER, str VARCHAR)",
            expected_local_type="UNION(num INT, str TEXT)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb list angle syntax maps to bracket list syntax",
            sql_analysis_dialect="duckdb",
            warehouse_type="LIST<INTEGER>",
            expected_local_type="INT[]",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb enum is preserved",
            sql_analysis_dialect="duckdb",
            warehouse_type="ENUM('a', 'b')",
            expected_local_type="ENUM('a', 'b')",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb time with timezone maps to timetz",
            sql_analysis_dialect="duckdb",
            warehouse_type="TIME WITH TIME ZONE",
            expected_local_type="TIMETZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="unknown type falls back to varchar",
            sql_analysis_dialect=None,
            warehouse_type="WIDGET",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="exact override wins over sql_analysis mapping",
            sql_analysis_dialect="snowflake",
            warehouse_type="OBJECT",
            expected_local_type="VARCHAR",
            local_type_overrides={"OBJECT": "VARCHAR"},
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="wildcard argument override maps scale zero number to bigint",
            sql_analysis_dialect="snowflake",
            warehouse_type="NUMBER(18,0)",
            expected_local_type="BIGINT",
            local_type_overrides={"NUMBER(*,0)": "BIGINT"},
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="exact argument override beats wildcard argument override",
            sql_analysis_dialect="snowflake",
            warehouse_type="NUMBER(38,0)",
            expected_local_type="DECIMAL(38, 0)",
            local_type_overrides={
                "NUMBER(*,0)": "BIGINT",
                "NUMBER(38,0)": "DECIMAL(38, 0)",
            },
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="override local type can reuse matched arguments",
            sql_analysis_dialect="bigquery",
            warehouse_type="BIGNUMERIC(38,9)",
            expected_local_type="DECIMAL(38, 9)",
            local_type_overrides={"BIGNUMERIC(*,*)": "DECIMAL({1}, {2})"},
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="angle bracket wildcard override maps arrays to json",
            sql_analysis_dialect="bigquery",
            warehouse_type="ARRAY<INT64>",
            expected_local_type="JSON",
            local_type_overrides={"ARRAY<*>": "JSON"},
        ),
    ],
    ids=lambda case: case.description,
)
def test_given_warehouse_type_when_mapping_to_local_type_then_returns_expected_duckdb_type(
    test_case: ScenarioSnapshotLocalTypeMappingTestCase,
) -> None:
    local_type: str = local_type_for_warehouse_type(
        warehouse_type=test_case.warehouse_type,
        sql_analysis_dialect=test_case.sql_analysis_dialect,
        local_type_overrides=test_case.local_type_overrides,
    )

    assert local_type == test_case.expected_local_type


@pytest.mark.parametrize(
    "test_case",
    [
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake number preserves default integer precision",
            sql_analysis_dialect="snowflake",
            warehouse_type="NUMBER",
            expected_local_type="DECIMAL(38, 0)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake number preserves explicit precision and scale",
            sql_analysis_dialect="snowflake",
            warehouse_type="NUMBER(10,2)",
            expected_local_type="DECIMAL(10, 2)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake decimal preserves explicit precision and scale",
            sql_analysis_dialect="snowflake",
            warehouse_type="DECIMAL(12,4)",
            expected_local_type="DECIMAL(12, 4)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake numeric preserves explicit integer scale",
            sql_analysis_dialect="snowflake",
            warehouse_type="NUMERIC(9,0)",
            expected_local_type="DECIMAL(9, 0)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake int maps to int",
            sql_analysis_dialect="snowflake",
            warehouse_type="INT",
            expected_local_type="INT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake bigint maps to bigint",
            sql_analysis_dialect="snowflake",
            warehouse_type="BIGINT",
            expected_local_type="BIGINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake boolean maps to boolean",
            sql_analysis_dialect="snowflake",
            warehouse_type="BOOLEAN",
            expected_local_type="BOOLEAN",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake float preserves double precision",
            sql_analysis_dialect="snowflake",
            warehouse_type="FLOAT",
            expected_local_type="DOUBLE",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake float4 remains real",
            sql_analysis_dialect="snowflake",
            warehouse_type="FLOAT4",
            expected_local_type="REAL",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake float8 maps to double",
            sql_analysis_dialect="snowflake",
            warehouse_type="FLOAT8",
            expected_local_type="DOUBLE",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake real remains real",
            sql_analysis_dialect="snowflake",
            warehouse_type="REAL",
            expected_local_type="REAL",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake varchar maps through sql_analysis text",
            sql_analysis_dialect="snowflake",
            warehouse_type="VARCHAR",
            expected_local_type="TEXT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake varchar length is preserved",
            sql_analysis_dialect="snowflake",
            warehouse_type="VARCHAR(255)",
            expected_local_type="TEXT(255)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake string maps to text",
            sql_analysis_dialect="snowflake",
            warehouse_type="STRING",
            expected_local_type="TEXT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake binary falls back to varchar for jsonl replay",
            sql_analysis_dialect="snowflake",
            warehouse_type="BINARY",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake date maps to date",
            sql_analysis_dialect="snowflake",
            warehouse_type="DATE",
            expected_local_type="DATE",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake time maps to time",
            sql_analysis_dialect="snowflake",
            warehouse_type="TIME",
            expected_local_type="TIME",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake timestamp ntz maps to timestamp",
            sql_analysis_dialect="snowflake",
            warehouse_type="TIMESTAMP_NTZ",
            expected_local_type="TIMESTAMP",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake timestamp ltz maps to timestamptz",
            sql_analysis_dialect="snowflake",
            warehouse_type="TIMESTAMP_LTZ",
            expected_local_type="TIMESTAMPTZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake timestamp ltz precision drops unsupported timestamptz parameter",
            sql_analysis_dialect="snowflake",
            warehouse_type="TIMESTAMP_LTZ(9)",
            expected_local_type="TIMESTAMPTZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake timestamp ntz precision is preserved",
            sql_analysis_dialect="snowflake",
            warehouse_type="TIMESTAMP_NTZ(9)",
            expected_local_type="TIMESTAMP(9)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake timestamp with timezone maps to timestamptz",
            sql_analysis_dialect="snowflake",
            warehouse_type="TIMESTAMP_TZ",
            expected_local_type="TIMESTAMPTZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake object falls back to json",
            sql_analysis_dialect="snowflake",
            warehouse_type="OBJECT",
            expected_local_type="JSON",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake bare array falls back to json",
            sql_analysis_dialect="snowflake",
            warehouse_type="ARRAY",
            expected_local_type="JSON",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake variant remains variant",
            sql_analysis_dialect="snowflake",
            warehouse_type="VARIANT",
            expected_local_type="VARIANT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake geography falls back to varchar",
            sql_analysis_dialect="snowflake",
            warehouse_type="GEOGRAPHY",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake geometry falls back to varchar for jsonl replay",
            sql_analysis_dialect="snowflake",
            warehouse_type="GEOMETRY",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="snowflake vector falls back to json",
            sql_analysis_dialect="snowflake",
            warehouse_type="VECTOR(FLOAT, 3)",
            expected_local_type="JSON",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery int64 maps to bigint",
            sql_analysis_dialect="bigquery",
            warehouse_type="INT64",
            expected_local_type="BIGINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery integer maps to int",
            sql_analysis_dialect="bigquery",
            warehouse_type="INTEGER",
            expected_local_type="INT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery boolean maps to boolean",
            sql_analysis_dialect="bigquery",
            warehouse_type="BOOL",
            expected_local_type="BOOLEAN",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery float64 maps to double",
            sql_analysis_dialect="bigquery",
            warehouse_type="FLOAT64",
            expected_local_type="DOUBLE",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery numeric maps to decimal",
            sql_analysis_dialect="bigquery",
            warehouse_type="NUMERIC",
            expected_local_type="DECIMAL",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery numeric explicit precision and scale are preserved",
            sql_analysis_dialect="bigquery",
            warehouse_type="NUMERIC(10,2)",
            expected_local_type="DECIMAL(10, 2)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery bignumeric default maps to wide decimal",
            sql_analysis_dialect="bigquery",
            warehouse_type="BIGNUMERIC",
            expected_local_type="DECIMAL(38, 5)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery bignumeric explicit scale avoids malformed sql_analysis rendering",
            sql_analysis_dialect="bigquery",
            warehouse_type="BIGNUMERIC(38,9)",
            expected_local_type="DECIMAL(38, 9)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery date range falls back to varchar",
            sql_analysis_dialect="bigquery",
            warehouse_type="RANGE<DATE>",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery datetime range falls back to varchar",
            sql_analysis_dialect="bigquery",
            warehouse_type="RANGE<DATETIME>",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery timestamp range falls back to varchar",
            sql_analysis_dialect="bigquery",
            warehouse_type="RANGE<TIMESTAMP>",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery array maps to duckdb list type",
            sql_analysis_dialect="bigquery",
            warehouse_type="ARRAY<INT64>",
            expected_local_type="BIGINT[]",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery string maps to text",
            sql_analysis_dialect="bigquery",
            warehouse_type="STRING",
            expected_local_type="TEXT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery bytes falls back to varchar for jsonl replay",
            sql_analysis_dialect="bigquery",
            warehouse_type="BYTES",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery parameterized bytes falls back to varchar for jsonl replay",
            sql_analysis_dialect="bigquery",
            warehouse_type="BYTES(10)",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery json maps to json",
            sql_analysis_dialect="bigquery",
            warehouse_type="JSON",
            expected_local_type="JSON",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery date maps to date",
            sql_analysis_dialect="bigquery",
            warehouse_type="DATE",
            expected_local_type="DATE",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery datetime maps to timestamp",
            sql_analysis_dialect="bigquery",
            warehouse_type="DATETIME",
            expected_local_type="TIMESTAMP",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery timestamp maps to timestamptz",
            sql_analysis_dialect="bigquery",
            warehouse_type="TIMESTAMP",
            expected_local_type="TIMESTAMPTZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery struct maps to duckdb struct type",
            sql_analysis_dialect="bigquery",
            warehouse_type="STRUCT<a INT64>",
            expected_local_type="STRUCT(a BIGINT)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery nested array of struct maps to duckdb list of struct",
            sql_analysis_dialect="bigquery",
            warehouse_type="ARRAY<STRUCT<a INT64, b STRING>>",
            expected_local_type="STRUCT(a BIGINT, b TEXT)[]",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="bigquery geography falls back to varchar",
            sql_analysis_dialect="bigquery",
            warehouse_type="GEOGRAPHY",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres smallint maps to smallint",
            sql_analysis_dialect="postgres",
            warehouse_type="smallint",
            expected_local_type="SMALLINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres integer maps to int",
            sql_analysis_dialect="postgres",
            warehouse_type="integer",
            expected_local_type="INT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres bigint maps to bigint",
            sql_analysis_dialect="postgres",
            warehouse_type="bigint",
            expected_local_type="BIGINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres real remains real",
            sql_analysis_dialect="postgres",
            warehouse_type="real",
            expected_local_type="REAL",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres double precision maps to double",
            sql_analysis_dialect="postgres",
            warehouse_type="double precision",
            expected_local_type="DOUBLE",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres numeric maps to decimal",
            sql_analysis_dialect="postgres",
            warehouse_type="numeric",
            expected_local_type="DECIMAL",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres numeric precision and scale are preserved",
            sql_analysis_dialect="postgres",
            warehouse_type="numeric(10,2)",
            expected_local_type="DECIMAL(10, 2)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres text maps to text",
            sql_analysis_dialect="postgres",
            warehouse_type="text",
            expected_local_type="TEXT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres varchar length maps to text length",
            sql_analysis_dialect="postgres",
            warehouse_type="varchar(255)",
            expected_local_type="TEXT(255)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres timestamp with time zone maps to timestamptz",
            sql_analysis_dialect="postgres",
            warehouse_type="timestamp with time zone",
            expected_local_type="TIMESTAMPTZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres jsonb maps to json",
            sql_analysis_dialect="postgres",
            warehouse_type="jsonb",
            expected_local_type="JSON",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres bytea falls back to varchar for jsonl replay",
            sql_analysis_dialect="postgres",
            warehouse_type="bytea",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres uuid maps to uuid",
            sql_analysis_dialect="postgres",
            warehouse_type="uuid",
            expected_local_type="UUID",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres inet maps to inet",
            sql_analysis_dialect="postgres",
            warehouse_type="inet",
            expected_local_type="INET",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres interval maps to interval",
            sql_analysis_dialect="postgres",
            warehouse_type="interval",
            expected_local_type="INTERVAL",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres macaddr falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="macaddr",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres macaddr8 falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="macaddr8",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres xml falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="xml",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres integer array maps to int list",
            sql_analysis_dialect="postgres",
            warehouse_type="integer[]",
            expected_local_type="INT[]",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres geography parse failure falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="geography",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres geometry falls back to varchar for jsonl replay",
            sql_analysis_dialect="postgres",
            warehouse_type="geometry",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres money falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="money",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres serial maps to int",
            sql_analysis_dialect="postgres",
            warehouse_type="serial",
            expected_local_type="INT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres bigserial maps to bigint",
            sql_analysis_dialect="postgres",
            warehouse_type="bigserial",
            expected_local_type="BIGINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres smallserial maps to smallint",
            sql_analysis_dialect="postgres",
            warehouse_type="smallserial",
            expected_local_type="SMALLINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres int4range falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="int4range",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres tstzrange falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="tstzrange",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres name falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="name",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres regclass falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="regclass",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres point falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="point",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="postgres cidr parse failure falls back to varchar",
            sql_analysis_dialect="postgres",
            warehouse_type="cidr",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks map maps to duckdb map type",
            sql_analysis_dialect="databricks",
            warehouse_type="MAP<STRING, INT>",
            expected_local_type="MAP(TEXT, INT)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks tinyint maps to tinyint",
            sql_analysis_dialect="databricks",
            warehouse_type="TINYINT",
            expected_local_type="TINYINT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks decimal precision and scale are preserved",
            sql_analysis_dialect="databricks",
            warehouse_type="DECIMAL(10,2)",
            expected_local_type="DECIMAL(10, 2)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks string maps to text",
            sql_analysis_dialect="databricks",
            warehouse_type="STRING",
            expected_local_type="TEXT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks varchar length maps to text length",
            sql_analysis_dialect="databricks",
            warehouse_type="VARCHAR(20)",
            expected_local_type="TEXT(20)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks timestamp maps to timestamptz",
            sql_analysis_dialect="databricks",
            warehouse_type="TIMESTAMP",
            expected_local_type="TIMESTAMPTZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks timestamp ntz maps to timestamp",
            sql_analysis_dialect="databricks",
            warehouse_type="TIMESTAMP_NTZ",
            expected_local_type="TIMESTAMP",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks array maps to duckdb list type",
            sql_analysis_dialect="databricks",
            warehouse_type="ARRAY<INT>",
            expected_local_type="INT[]",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks struct maps to duckdb struct type",
            sql_analysis_dialect="databricks",
            warehouse_type="STRUCT<a: INT>",
            expected_local_type="STRUCT(a INT)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks variant is preserved when duckdb supports it",
            sql_analysis_dialect="databricks",
            warehouse_type="VARIANT",
            expected_local_type="VARIANT",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks void falls back to varchar",
            sql_analysis_dialect="databricks",
            warehouse_type="VOID",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks nested map of arrays maps to duckdb map",
            sql_analysis_dialect="databricks",
            warehouse_type="MAP<STRING, ARRAY<INT>>",
            expected_local_type="MAP(TEXT, INT[])",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks interval year is preserved",
            sql_analysis_dialect="databricks",
            warehouse_type="INTERVAL YEAR",
            expected_local_type="INTERVAL YEAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks geography parse failure falls back to varchar",
            sql_analysis_dialect="databricks",
            warehouse_type="GEOGRAPHY",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="databricks geometry falls back to varchar for jsonl replay",
            sql_analysis_dialect="databricks",
            warehouse_type="GEOMETRY",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb hugeint maps to duckdb int128 alias",
            sql_analysis_dialect="duckdb",
            warehouse_type="HUGEINT",
            expected_local_type="INT128",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb unsigned integer is preserved",
            sql_analysis_dialect="duckdb",
            warehouse_type="UINTEGER",
            expected_local_type="UINTEGER",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb unsigned hugeint maps to uint128 alias",
            sql_analysis_dialect="duckdb",
            warehouse_type="UHUGEINT",
            expected_local_type="UINT128",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb timestamp ns is preserved",
            sql_analysis_dialect="duckdb",
            warehouse_type="TIMESTAMP_NS",
            expected_local_type="TIMESTAMP_NS",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb blob falls back to varchar for jsonl replay",
            sql_analysis_dialect="duckdb",
            warehouse_type="BLOB",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb struct is preserved with normalized inner type",
            sql_analysis_dialect="duckdb",
            warehouse_type="STRUCT(a INTEGER)",
            expected_local_type="STRUCT(a INT)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb union is preserved with normalized inner types",
            sql_analysis_dialect="duckdb",
            warehouse_type="UNION(num INTEGER, str VARCHAR)",
            expected_local_type="UNION(num INT, str TEXT)",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb list angle syntax maps to bracket list syntax",
            sql_analysis_dialect="duckdb",
            warehouse_type="LIST<INTEGER>",
            expected_local_type="INT[]",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb enum is preserved",
            sql_analysis_dialect="duckdb",
            warehouse_type="ENUM('a', 'b')",
            expected_local_type="ENUM('a', 'b')",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="duckdb time with timezone maps to timetz",
            sql_analysis_dialect="duckdb",
            warehouse_type="TIME WITH TIME ZONE",
            expected_local_type="TIMETZ",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="unknown type falls back to varchar",
            sql_analysis_dialect=None,
            warehouse_type="WIDGET",
            expected_local_type="VARCHAR",
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="exact override wins over sql_analysis mapping",
            sql_analysis_dialect="snowflake",
            warehouse_type="OBJECT",
            expected_local_type="VARCHAR",
            local_type_overrides={"OBJECT": "VARCHAR"},
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="wildcard argument override maps scale zero number to bigint",
            sql_analysis_dialect="snowflake",
            warehouse_type="NUMBER(18,0)",
            expected_local_type="BIGINT",
            local_type_overrides={"NUMBER(*,0)": "BIGINT"},
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="exact argument override beats wildcard argument override",
            sql_analysis_dialect="snowflake",
            warehouse_type="NUMBER(38,0)",
            expected_local_type="DECIMAL(38, 0)",
            local_type_overrides={
                "NUMBER(*,0)": "BIGINT",
                "NUMBER(38,0)": "DECIMAL(38, 0)",
            },
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="override local type can reuse matched arguments",
            sql_analysis_dialect="bigquery",
            warehouse_type="BIGNUMERIC(38,9)",
            expected_local_type="DECIMAL(38, 9)",
            local_type_overrides={"BIGNUMERIC(*,*)": "DECIMAL({1}, {2})"},
        ),
        ScenarioSnapshotLocalTypeMappingTestCase(
            description="angle bracket wildcard override maps arrays to json",
            sql_analysis_dialect="bigquery",
            warehouse_type="ARRAY<INT64>",
            expected_local_type="JSON",
            local_type_overrides={"ARRAY<*>": "JSON"},
        ),
    ],
    ids=lambda case: case.description,
)
def test_given_mapped_local_type_when_creating_duckdb_table_then_type_is_accepted(
    test_case: ScenarioSnapshotLocalTypeMappingTestCase,
) -> None:
    local_type: str = local_type_for_warehouse_type(
        warehouse_type=test_case.warehouse_type,
        sql_analysis_dialect=test_case.sql_analysis_dialect,
        local_type_overrides=test_case.local_type_overrides,
    )
    connection: duckdb.DuckDBPyConnection = duckdb.connect(":memory:")

    assert local_type == test_case.expected_local_type
    connection.execute(f'CREATE TABLE local_type_probe ("value" {local_type})')
