"""Range computation and Rust rendering of Python's `str.isalnum()` table."""

from __future__ import annotations

import unicodedata

from scripts.python_char_table.constants import MAX_CODE_POINT


def alnum_ranges() -> list[tuple[int, int]]:
    """Return the inclusive code point ranges where `str.isalnum()` is true."""

    ranges: list[tuple[int, int]] = []
    start: int | None = None
    for code_point in range(MAX_CODE_POINT + 1):
        alnum: bool = chr(code_point).isalnum()
        if alnum and start is None:
            start = code_point
        elif not alnum and start is not None:
            ranges.append((start, code_point - 1))
            start = None
    if start is not None:
        ranges.append((start, MAX_CODE_POINT))
    return ranges


def render_table(ranges: list[tuple[int, int]]) -> str:
    """Render the Rust source of the range table."""

    lines: list[str] = [
        "//! Generated by `scripts/generate_python_char_table.py`; do not edit.",
        "",
        "/// The Unicode version of the Python that generated the table.",
        f'pub(crate) const PYTHON_ALNUM_UNICODE_VERSION: &str = "{unicodedata.unidata_version}";',
        "",
        "/// Inclusive code point ranges where Python's `str.isalnum()` is true, in order.",
        "pub(crate) const PYTHON_ALNUM_RANGES: &[(u32, u32)] = &[",
    ]
    lines.extend(f"    (0x{start:04X}, 0x{end:04X})," for start, end in ranges)
    lines.append("];")
    return "\n".join(lines) + "\n"
