"""Range and mapping computation, and Rust rendering, of Python's `str` character tables."""

from __future__ import annotations

import unicodedata
from pathlib import Path

from scripts.python_char_table.constants import (
    MAX_CODE_POINT,
    SURROGATE_RANGE,
    TABLE_FILE_PREFIX,
    TABLE_FILE_SUFFIX,
    TABLE_ROOT,
)


def table_path(*, method: str) -> Path:
    """Return the Rust file holding one method's table for the running Python's Unicode version."""

    version: str = unicodedata.unidata_version.replace(".", "_")
    directory: Path = TABLE_ROOT / f"{method.removeprefix('is')}_ranges"
    return directory / f"{TABLE_FILE_PREFIX}{version}{TABLE_FILE_SUFFIX}"


def mapping_path(*, method: str) -> Path:
    """Return the Rust file holding one case mapping for the running Python's Unicode version."""

    version: str = unicodedata.unidata_version.replace(".", "_")
    return TABLE_ROOT / f"{method}_mappings" / f"{TABLE_FILE_PREFIX}{version}{TABLE_FILE_SUFFIX}"


def character_mappings(*, method: str) -> list[tuple[int, str]]:
    """Return every character the `str` method changes, with what it becomes, in order."""

    mappings: list[tuple[int, str]] = []
    for code_point in range(MAX_CODE_POINT + 1):
        if code_point in SURROGATE_RANGE:
            continue
        character: str = chr(code_point)
        mapped: str = getattr(character, method)()
        if mapped != character:
            mappings.append((code_point, mapped))
    return mappings


def render_mapping(*, method: str, mappings: list[tuple[int, str]]) -> str:
    """Render the Rust expression of one case mapping table, which `case_tables.rs` includes."""

    lines: list[str] = [
        "// Generated by `scripts/generate_python_char_table.py`; do not edit.",
        f"// Every character `str.{method}()` changes in Unicode {unicodedata.unidata_version}, "
        "in code point order.",
        "&[",
    ]
    lines.extend(
        f'    (0x{code_point:04X}, "{_rust_escaped(mapped)}"),' for code_point, mapped in mappings
    )
    lines.append("]")
    return "\n".join(lines) + "\n"


def character_ranges(*, method: str) -> list[tuple[int, int]]:
    """Return the inclusive code point ranges where the `str` method is true."""

    ranges: list[tuple[int, int]] = []
    start: int | None = None
    for code_point in range(MAX_CODE_POINT + 1):
        matched: bool = getattr(chr(code_point), method)()
        if matched and start is None:
            start = code_point
        elif not matched and start is not None:
            ranges.append((start, code_point - 1))
            start = None
    if start is not None:
        ranges.append((start, MAX_CODE_POINT))
    return ranges


def render_table(*, method: str, ranges: list[tuple[int, int]]) -> str:
    """Render the Rust expression of one range table, which `alnum_tables.rs` includes."""

    lines: list[str] = [
        "// Generated by `scripts/generate_python_char_table.py`; do not edit.",
        f"// Inclusive code point ranges where `str.{method}()` is true in Unicode "
        f"{unicodedata.unidata_version}, in order.",
        "&[",
    ]
    lines.extend(f"    (0x{start:04X}, 0x{end:04X})," for start, end in ranges)
    lines.append("]")
    return "\n".join(lines) + "\n"


def _rust_escaped(text: str) -> str:
    return "".join(f"\\u{{{ord(character):x}}}" for character in text)
