"""Shared cross-cutting constants."""

from __future__ import annotations

LOGGER_ROOT_NAME: str = "sqlbuild"
SCENARIO_ARTIFACT_PREFIX: str = "__sqb_"
SCENARIO_HASH_PREFIX_LENGTH: int = 12
SCENARIO_SHORTENED_LOGICAL_HASH_LENGTH: int = 8
SCENARIO_ARTIFACT_KINDS: tuple[str, ...] = ("source", "ref", "seed", "model")

# Scenario CLI codes use the existing C45x range.
SCENARIO_CLI_MISSING_SUBCOMMAND: str = "C450"
SCENARIO_CLI_NONE_DISCOVERED: str = "C451"
SCENARIO_CLI_LOCAL_RETAIN_UNSUPPORTED: str = "C452"
SCENARIO_CLI_UNKNOWN_SELECTOR: str = "C453"

# Scenario planning codes use the S5xx range.
SCENARIO_PLAN_INVALID_HASH_PREFIX: str = "S501"
SCENARIO_PLAN_HASH_COLLISION: str = "S502"
SCENARIO_PLAN_RELATION_COLLISION: str = "S503"
SCENARIO_PLAN_GRAPH_VALIDATION: str = "S504"
SCENARIO_PLAN_SQLGLOT_UNAVAILABLE: str = "S505"
SCENARIO_PLAN_SQLGLOT_PARSE: str = "S506"
SCENARIO_PLAN_UNKNOWN_SEED: str = "S507"
SCENARIO_PLAN_MISSING_FIXTURE_SQL: str = "S508"
SCENARIO_PLAN_MISSING_RELATION_TARGET: str = "S509"
SCENARIO_PLAN_INTERNAL: str = "S599"

# Remote scenario execution codes use the X5xx range.
SCENARIO_EXEC_FIXTURE_FAILED: str = "X501"
SCENARIO_EXEC_SEED_FAILED: str = "X502"
SCENARIO_EXEC_MODEL_FAILED: str = "X503"
SCENARIO_EXEC_EXPECTED_ERRORED: str = "X504"
SCENARIO_EXEC_EXPECTED_INTERNAL: str = "X505"
SCENARIO_EXEC_EXPECTED_FAILED: str = "X506"
SCENARIO_EXEC_ASSERTION_ERRORED: str = "X507"
SCENARIO_EXEC_ASSERTION_FAILED: str = "X508"
SCENARIO_EXEC_CLEANUP_FAILED: str = "X509"
SCENARIO_EXEC_CAPTURE_FAILED: str = "X510"
SCENARIO_EXEC_CAPTURE_INTERNAL: str = "X511"
SCENARIO_EXEC_INTERNAL: str = "X599"

# Local scenario snapshot/replay codes use the X6xx range.
SCENARIO_LOCAL_SNAPSHOT_MISSING: str = "X601"
SCENARIO_LOCAL_SNAPSHOT_STALE: str = "X602"
SCENARIO_LOCAL_MANIFEST_INVALID: str = "X603"
SCENARIO_LOCAL_JSONL_INVALID: str = "X604"
SCENARIO_LOCAL_TYPE_INVALID: str = "X605"
SCENARIO_LOCAL_LOAD_FAILED: str = "X606"
SCENARIO_LOCAL_SQL_TRANSPILE_FAILED: str = "X607"
SCENARIO_LOCAL_MODEL_FAILED: str = "X608"
SCENARIO_LOCAL_FUNCTION_FAILED: str = "X609"
SCENARIO_LOCAL_INTERNAL: str = "X699"
