"""Shared cross-cutting constants."""

from __future__ import annotations

LOGGER_ROOT_NAME: str = "sqlbuild"
DEFAULT_MAX_DISPLAY_ENTRIES: int = 20
SCENARIO_ARTIFACT_PREFIX: str = "__sqb_"
SCENARIO_HASH_PREFIX_LENGTH: int = 12
SCENARIO_SHORTENED_LOGICAL_HASH_LENGTH: int = 8
SCENARIO_ARTIFACT_KINDS: tuple[str, ...] = ("source", "ref", "seed", "dbt_ref", "model")

POLYGLOT_KIND_ALIAS: str = "alias"
POLYGLOT_KIND_ARRAY_AGG: str = "array_agg"
POLYGLOT_KIND_AVG: str = "avg"
POLYGLOT_KIND_CAST: str = "cast"
POLYGLOT_KIND_COALESCE: str = "coalesce"
POLYGLOT_KIND_COLUMN: str = "column"
POLYGLOT_KIND_COUNT: str = "count"
POLYGLOT_KIND_EXCEPT: str = "except"
POLYGLOT_KIND_INTERSECT: str = "intersect"
POLYGLOT_KIND_LITERAL: str = "literal"
POLYGLOT_KIND_MAX: str = "max"
POLYGLOT_KIND_MIN: str = "min"
POLYGLOT_KIND_NULL: str = "null"
POLYGLOT_KIND_SELECT: str = "select"
POLYGLOT_KIND_STRING_AGG: str = "string_agg"
POLYGLOT_KIND_SUM: str = "sum"
POLYGLOT_KIND_TABLE: str = "table"
POLYGLOT_KIND_TRY_CAST: str = "try_cast"
POLYGLOT_KIND_UNION: str = "union"
POLYGLOT_SET_OPERATION_KINDS: frozenset[str] = frozenset(
    {POLYGLOT_KIND_UNION, POLYGLOT_KIND_INTERSECT, POLYGLOT_KIND_EXCEPT}
)
POLYGLOT_CAST_KINDS: frozenset[str] = frozenset({POLYGLOT_KIND_CAST, POLYGLOT_KIND_TRY_CAST})
POLYGLOT_AGGREGATE_KINDS: frozenset[str] = frozenset(
    {
        POLYGLOT_KIND_AVG,
        POLYGLOT_KIND_COUNT,
        POLYGLOT_KIND_MAX,
        POLYGLOT_KIND_MIN,
        POLYGLOT_KIND_SUM,
        POLYGLOT_KIND_ARRAY_AGG,
        POLYGLOT_KIND_STRING_AGG,
    }
)
POLYGLOT_PAYLOAD_ALIAS: str = "alias"
POLYGLOT_PAYLOAD_COLUMN: str = "column"
POLYGLOT_PAYLOAD_DATA_TYPE: str = "data_type"
POLYGLOT_PAYLOAD_FROM: str = "from"
POLYGLOT_PAYLOAD_EXPRESSIONS: str = "expressions"
POLYGLOT_PAYLOAD_JOINS: str = "joins"
POLYGLOT_PAYLOAD_KIND: str = "kind"
POLYGLOT_PAYLOAD_NAME: str = "name"
POLYGLOT_PAYLOAD_PRECISION: str = "precision"
POLYGLOT_PAYLOAD_SCALE: str = "scale"
POLYGLOT_PAYLOAD_SELECT: str = "select"
POLYGLOT_PAYLOAD_TABLE: str = "table"
POLYGLOT_PAYLOAD_THIS: str = "this"
POLYGLOT_PAYLOAD_TO: str = "to"
POLYGLOT_JOIN_FULL: str = "FULL"
POLYGLOT_JOIN_LEFT: str = "LEFT"
POLYGLOT_JOIN_RIGHT: str = "RIGHT"
POLYGLOT_ANALYSIS_BASE_TABLES: str = "baseTables"
POLYGLOT_ANALYSIS_BODY_SQL: str = "bodySql"
POLYGLOT_ANALYSIS_CAST_TYPE: str = "castType"
POLYGLOT_ANALYSIS_CTES: str = "ctes"
POLYGLOT_ANALYSIS_CTE_FACTS: str = "cteFacts"
POLYGLOT_ANALYSIS_IS_STAR: str = "isStar"
POLYGLOT_ANALYSIS_NAME: str = "name"
POLYGLOT_ANALYSIS_NULLABILITY: str = "nullability"
POLYGLOT_ANALYSIS_NULLABILITY_NON_NULL: str = "non_null"
POLYGLOT_ANALYSIS_NULLABILITY_NULLABLE: str = "nullable"
POLYGLOT_ANALYSIS_NULLABILITY_UNKNOWN: str = "unknown"
POLYGLOT_ANALYSIS_PROJECTIONS: str = "projections"
POLYGLOT_ANALYSIS_RELATIONS: str = "relations"
POLYGLOT_ANALYSIS_SET_OPERATIONS: str = "setOperations"
POLYGLOT_ANALYSIS_SHAPE: str = "shape"
POLYGLOT_ANALYSIS_SOURCE_ALIAS: str = "sourceAlias"
POLYGLOT_ANALYSIS_SOURCE_CONFIDENCE: str = "confidence"
POLYGLOT_ANALYSIS_SOURCE_NAME: str = "sourceName"
POLYGLOT_ANALYSIS_TABLE: str = "table"
POLYGLOT_ANALYSIS_TRANSFORM_KIND: str = "transformKind"
POLYGLOT_ANALYSIS_STAR_PROJECTIONS: str = "starProjections"
POLYGLOT_ANALYSIS_TYPE_HINT: str = "typeHint"
POLYGLOT_ANALYSIS_UPSTREAM: str = "upstream"
POLYGLOT_ANALYSIS_SHAPE_SELECT: str = "select"
POLYGLOT_ANALYSIS_SHAPE_SET_OPERATION: str = "set_operation"
POLYGLOT_ANALYSIS_TRANSFORM_AGGREGATION: str = "aggregation"
POLYGLOT_ANALYSIS_TRANSFORM_CAST: str = "cast"
POLYGLOT_ANALYSIS_TRANSFORM_CONSTANT: str = "constant"
POLYGLOT_ANALYSIS_TRANSFORM_DIRECT: str = "direct"
POLYGLOT_ANALYSIS_TRANSFORM_EXPRESSION: str = "expression"
POLYGLOT_ANALYSIS_TRANSFORM_STAR: str = "star"
POLYGLOT_ANALYSIS_UNSAFE_TRANSFORMS: frozenset[str] = frozenset()

# Scenario CLI codes use the existing C45x range.
SCENARIO_CLI_MISSING_SUBCOMMAND: str = "C450"
SCENARIO_CLI_NONE_DISCOVERED: str = "C451"
SCENARIO_CLI_LOCAL_RETAIN_UNSUPPORTED: str = "C452"
SCENARIO_CLI_UNKNOWN_SELECTOR: str = "C453"
SCENARIO_CLI_LOCAL_SNAPSHOT_FLAG_REQUIRED: str = "C454"
SCENARIO_CLI_SQL_VALIDATION_REQUIRED: str = "C455"
SCENARIO_CLI_CAPTURE_DIALECT_REQUIRED: str = "C456"
SCENARIO_CLI_UNSUPPORTED_GRAPH_SELECTOR: str = "C457"

# Scenario planning codes use the S5xx range.
SCENARIO_PLAN_INVALID_HASH_PREFIX: str = "S501"
SCENARIO_PLAN_HASH_COLLISION: str = "S502"
SCENARIO_PLAN_RELATION_COLLISION: str = "S503"
SCENARIO_PLAN_GRAPH_VALIDATION: str = "S504"
SCENARIO_PLAN_SQLGLOT_UNAVAILABLE: str = "S505"
SCENARIO_PLAN_SQLGLOT_PARSE: str = "S506"
SCENARIO_PLAN_UNKNOWN_SEED: str = "S507"
SCENARIO_PLAN_MISSING_FIXTURE_SQL: str = "S508"
SCENARIO_PLAN_MISSING_RELATION_TARGET: str = "S509"
SCENARIO_PLAN_INTERNAL: str = "S599"

# Remote scenario execution codes use the X5xx range.
SCENARIO_EXEC_FIXTURE_FAILED: str = "X501"
SCENARIO_EXEC_SEED_FAILED: str = "X502"
SCENARIO_EXEC_MODEL_FAILED: str = "X503"
SCENARIO_EXEC_EXPECTED_ERRORED: str = "X504"
SCENARIO_EXEC_EXPECTED_INTERNAL: str = "X505"
SCENARIO_EXEC_EXPECTED_FAILED: str = "X506"
SCENARIO_EXEC_ASSERTION_ERRORED: str = "X507"
SCENARIO_EXEC_ASSERTION_FAILED: str = "X508"
SCENARIO_EXEC_CLEANUP_FAILED: str = "X509"
SCENARIO_EXEC_CAPTURE_FAILED: str = "X510"
SCENARIO_EXEC_CAPTURE_INTERNAL: str = "X511"
SCENARIO_EXEC_CAPTURE_LIMIT_EXCEEDED: str = "X512"
SCENARIO_EXEC_INTERNAL: str = "X599"

# Local scenario snapshot/replay codes use the X6xx range.
SCENARIO_LOCAL_SNAPSHOT_MISSING: str = "X601"
SCENARIO_LOCAL_SNAPSHOT_STALE: str = "X602"
SCENARIO_LOCAL_MANIFEST_INVALID: str = "X603"
SCENARIO_LOCAL_JSONL_INVALID: str = "X604"
SCENARIO_LOCAL_TYPE_INVALID: str = "X605"
SCENARIO_LOCAL_LOAD_FAILED: str = "X606"
SCENARIO_LOCAL_SQL_TRANSPILE_FAILED: str = "X607"
SCENARIO_LOCAL_MODEL_FAILED: str = "X608"
SCENARIO_LOCAL_FUNCTION_FAILED: str = "X609"
SCENARIO_LOCAL_INTERNAL: str = "X699"
