//! Python's `str.isalnum()` for one character, from a table generated by Python.

use crate::text::_helpers::code_point_ranges::in_ranges;
use crate::text::models::PythonText;

/// Whether Python's `str.isalnum()` is true for one character.
pub fn is_python_alnum(python: PythonText, character: char) -> bool {
    if character.is_ascii() {
        return character.is_ascii_alphanumeric();
    }
    in_ranges(python.alnum_ranges, character)
}
