//! Python's `str.isalnum()` for one character, from a table generated by Python.

use crate::text::_helpers::alnum_ranges::PYTHON_ALNUM_RANGES;

/// Whether Python's `str.isalnum()` is true for one character.
pub fn is_python_alnum(character: char) -> bool {
    if character.is_ascii() {
        return character.is_ascii_alphanumeric();
    }
    let code_point: u32 = u32::from(character);
    let index: usize = PYTHON_ALNUM_RANGES.partition_point(|(_, end)| *end < code_point);
    PYTHON_ALNUM_RANGES
        .get(index)
        .is_some_and(|(start, _)| *start <= code_point)
}
