//! Python's `str.isalpha()` for one character, from a table generated by Python.

use crate::text::main::is_python_alnum::in_ranges;
use crate::text::models::PythonText;

/// Whether Python's `str.isalpha()` is true for one character.
pub fn is_python_alpha(python: PythonText, character: char) -> bool {
    if character.is_ascii() {
        return character.is_ascii_alphabetic();
    }
    in_ranges(python.alpha_ranges, character)
}
