//! Python's `re.IGNORECASE` character matching, from a table generated by Python.

use crate::text::models::PythonText;

/// The key under which `re.IGNORECASE` matches `character`: a pattern character matches a text
/// character exactly when both keys are equal.
pub fn python_ignorecase_key(python: PythonText, character: char) -> char {
    if character.is_ascii() {
        return character.to_ascii_lowercase();
    }
    let code_point: u32 = u32::from(character);
    python
        .ignorecase_keys
        .binary_search_by_key(&code_point, |(key, _)| *key)
        .ok()
        .and_then(|index| char::from_u32(python.ignorecase_keys[index].1))
        .unwrap_or(character)
}
