//! Python's `str.casefold()`, from a table generated by Python.

use crate::text::_helpers::case_tables::mapped;
use crate::text::models::PythonText;

/// Python's `text.casefold()`.
pub fn python_casefold(python: PythonText, text: &str) -> String {
    if text.is_ascii() {
        return text.to_ascii_lowercase();
    }
    mapped(python.casefold_mappings, text)
}
