//! Python's `str.upper()`, from a table generated by Python.

use crate::text::_helpers::case_tables::mapped;
use crate::text::models::PythonText;

/// Python's `text.upper()`.
pub fn python_upper(python: PythonText, text: &str) -> String {
    if text.is_ascii() {
        return text.to_ascii_uppercase();
    }
    mapped(python.upper_mappings, text)
}
