[package]
name = "sqlbuild-config"
version.workspace = true
description = "Project configuration reading for SQLBuild: TOML."
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
toml_edit.workspace = true
toml_parser.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
