adapter = "snowflake"
environment = "dev"

[connection]
account = "${ENV:SQB_TEST_SNOWFLAKE_ACCOUNT}"
user = "${ENV:SQB_TEST_SNOWFLAKE_USER}"
authenticator = "${ENV:SQB_TEST_SNOWFLAKE_AUTHENTICATOR}"
token = "${ENV:SQB_TEST_SNOWFLAKE_PAT}"
role = "${ENV:SQB_TEST_SNOWFLAKE_ROLE}"
warehouse = "${ENV:SQB_TEST_SNOWFLAKE_WAREHOUSE}"
database = "${ENV:SQB_TEST_SNOWFLAKE_DATABASE}"
schema = "${ENV:SQB_TEST_SNOWFLAKE_SCHEMA}"

[environments.dev]
database = "${ENV:SQB_TEST_SNOWFLAKE_DATABASE}"
schema = "${ENV:SQB_TEST_SNOWFLAKE_SCHEMA}"

# BigQuery example:
# adapter = "bigquery"
# environment = "dev"
#
# [connection]
# project = "${ENV:SQB_TEST_BIGQUERY_PROJECT}"
# location = "europe-west2"
#
# [environments.dev]
# database = "${ENV:SQB_TEST_BIGQUERY_PROJECT}"

# Databricks example:
# adapter = "databricks"
# environment = "dev"
#
# [connection]
# server_hostname = "${ENV:SQB_TEST_DATABRICKS_SERVER_HOSTNAME}"
# http_path = "${ENV:SQB_TEST_DATABRICKS_HTTP_PATH}"
# token = "${ENV:SQB_TEST_DATABRICKS_TOKEN}"
# catalog = "${ENV:SQB_TEST_DATABRICKS_CATALOG}"
#
# [environments.dev]
# database = "${ENV:SQB_TEST_DATABRICKS_CATALOG}"
# schema = "${ENV:SQB_TEST_DATABRICKS_SCHEMA}"
