"""Scenario command helper constants."""

SUCCESS_STATUS: str = "success"
FAILED_STATUS: str = "failed"
DEFAULT_MAX_SNAPSHOT_ROWS_PER_RELATION: int = 10_000
DEFAULT_MAX_SNAPSHOT_TOTAL_ROWS: int = 50_000
DEFAULT_MAX_SNAPSHOT_BYTES_PER_RELATION: int = 5_000_000
DEFAULT_MAX_SNAPSHOT_TOTAL_BYTES: int = 25_000_000
