name: jaffle_analytics
profile: jaffle_analytics
version: "1.0.0"
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: target

models:
  jaffle_analytics:
    +materialized: table
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts

seeds:
  jaffle_analytics:
    +schema: raw
