"""Unit tests for mapping rendered SQL offsets back onto authored text."""

from __future__ import annotations

import pytest

from sqlbuild.compiler.compile._helpers.render.spans import (
    map_output_offset,
    map_through_passes,
)
from sqlbuild.compiler.compile.models import ExpansionSpan, MappedOffset
from tests.unit.src.sqlbuild.compiler.compile._helpers._test_types import (
    MapOutputOffsetTestCase,
    MapThroughPassesTestCase,
)


@pytest.mark.parametrize(
    "test_case",
    [
        MapOutputOffsetTestCase(
            description="offset before any substitution is unchanged",
            spans=(ExpansionSpan(source_start=10, source_end=20, output_start=10, output_end=40),),
            offset=5,
            expected_offset=5,
            expected_generated=False,
        ),
        MapOutputOffsetTestCase(
            description="offset at a substitution start is authored and not generated",
            spans=(ExpansionSpan(source_start=10, source_end=20, output_start=10, output_end=40),),
            offset=10,
            expected_offset=10,
            expected_generated=True,
        ),
        MapOutputOffsetTestCase(
            description="offset inside generated text clamps to the substitution start",
            spans=(ExpansionSpan(source_start=10, source_end=20, output_start=10, output_end=40),),
            offset=25,
            expected_offset=10,
            expected_generated=True,
        ),
        MapOutputOffsetTestCase(
            description="offset after a growing substitution shifts back",
            spans=(ExpansionSpan(source_start=10, source_end=20, output_start=10, output_end=40),),
            offset=45,
            expected_offset=25,
            expected_generated=False,
        ),
        MapOutputOffsetTestCase(
            description="offset after a shrinking substitution shifts forward",
            spans=(ExpansionSpan(source_start=10, source_end=40, output_start=10, output_end=20),),
            offset=25,
            expected_offset=45,
            expected_generated=False,
        ),
        MapOutputOffsetTestCase(
            description="offsets after two substitutions accumulate both deltas",
            spans=(
                ExpansionSpan(source_start=10, source_end=20, output_start=10, output_end=40),
                ExpansionSpan(source_start=30, source_end=35, output_start=50, output_end=60),
            ),
            offset=65,
            expected_offset=40,
            expected_generated=False,
        ),
        MapOutputOffsetTestCase(
            description="no substitutions maps identically",
            spans=(),
            offset=17,
            expected_offset=17,
            expected_generated=False,
        ),
    ],
    ids=lambda case: case.description,
)
def test_given_rendered_offset_when_mapping_one_pass_then_source_offset_matches(
    test_case: MapOutputOffsetTestCase,
) -> None:
    resolved: MappedOffset = map_output_offset(offset=test_case.offset, spans=test_case.spans)
    assert resolved.offset == test_case.expected_offset
    assert resolved.generated == test_case.expected_generated


@pytest.mark.parametrize(
    "test_case",
    [
        MapThroughPassesTestCase(
            description="literal offset resolves through every pass unchanged",
            passes=(
                (ExpansionSpan(source_start=0, source_end=5, output_start=0, output_end=10),),
                (ExpansionSpan(source_start=20, source_end=25, output_start=25, output_end=40),),
            ),
            offset=0,
            expected_offset=0,
            expected_generated=True,
        ),
        MapThroughPassesTestCase(
            description="offset generated by the later pass is attributed to its call site",
            passes=(
                (ExpansionSpan(source_start=0, source_end=5, output_start=0, output_end=5),),
                (ExpansionSpan(source_start=20, source_end=25, output_start=20, output_end=60),),
            ),
            offset=40,
            expected_offset=20,
            expected_generated=True,
        ),
        MapThroughPassesTestCase(
            description="offset generated by the earlier pass stays marked generated",
            passes=(
                (ExpansionSpan(source_start=10, source_end=15, output_start=10, output_end=50),),
                (ExpansionSpan(source_start=80, source_end=85, output_start=80, output_end=90),),
            ),
            offset=30,
            expected_offset=10,
            expected_generated=True,
        ),
        MapThroughPassesTestCase(
            description="offset outside every substitution accumulates deltas across passes",
            passes=(
                (ExpansionSpan(source_start=10, source_end=20, output_start=10, output_end=30),),
                (ExpansionSpan(source_start=50, source_end=55, output_start=50, output_end=70),),
            ),
            offset=90,
            expected_offset=65,
            expected_generated=False,
        ),
        MapThroughPassesTestCase(
            description="passes without substitutions map identically",
            passes=((), ()),
            offset=12,
            expected_offset=12,
            expected_generated=False,
        ),
    ],
    ids=lambda case: case.description,
)
def test_given_rendered_offset_when_mapping_all_passes_then_authored_offset_matches(
    test_case: MapThroughPassesTestCase,
) -> None:
    resolved: MappedOffset = map_through_passes(offset=test_case.offset, passes=test_case.passes)
    assert resolved.offset == test_case.expected_offset
    assert resolved.generated == test_case.expected_generated
