"""Scenario execution and local replay constants."""

SCENARIO_EXEC_FIXTURE_FAILED: str = "X501"
SCENARIO_EXEC_SEED_FAILED: str = "X502"
SCENARIO_EXEC_MODEL_FAILED: str = "X503"
SCENARIO_EXEC_EXPECTED_ERRORED: str = "X504"
SCENARIO_EXEC_EXPECTED_INTERNAL: str = "X505"
SCENARIO_EXEC_EXPECTED_FAILED: str = "X506"
SCENARIO_EXEC_ASSERTION_ERRORED: str = "X507"
SCENARIO_EXEC_ASSERTION_FAILED: str = "X508"
SCENARIO_EXEC_CLEANUP_FAILED: str = "X509"
SCENARIO_EXEC_CAPTURE_FAILED: str = "X510"
SCENARIO_EXEC_CAPTURE_INTERNAL: str = "X511"
SCENARIO_EXEC_CAPTURE_LIMIT_EXCEEDED: str = "X512"
SCENARIO_EXEC_INTERNAL: str = "X599"
SCENARIO_LOCAL_SNAPSHOT_MISSING: str = "X601"
SCENARIO_LOCAL_SNAPSHOT_STALE: str = "X602"
SCENARIO_LOCAL_MANIFEST_INVALID: str = "X603"
SCENARIO_LOCAL_JSONL_INVALID: str = "X604"
SCENARIO_LOCAL_TYPE_INVALID: str = "X605"
SCENARIO_LOCAL_LOAD_FAILED: str = "X606"
SCENARIO_LOCAL_SQL_TRANSPILE_FAILED: str = "X607"
SCENARIO_LOCAL_MODEL_FAILED: str = "X608"
SCENARIO_LOCAL_FUNCTION_FAILED: str = "X609"
SCENARIO_LOCAL_INTERNAL: str = "X699"

LOCAL_TYPE_BIGINT: str = "BIGINT"
LOCAL_TYPE_BOOLEAN: str = "BOOLEAN"
LOCAL_TYPE_DATE: str = "DATE"
LOCAL_TYPE_DECIMAL: str = "DECIMAL"
LOCAL_TYPE_DOUBLE: str = "DOUBLE"
LOCAL_TYPE_INT: str = "INT"
LOCAL_TYPE_INT128: str = "INT128"
LOCAL_TYPE_JSON: str = "JSON"
LOCAL_TYPE_REAL: str = "REAL"
LOCAL_TYPE_SMALLINT: str = "SMALLINT"
LOCAL_TYPE_TEXT: str = "TEXT"
LOCAL_TYPE_TIME: str = "TIME"
LOCAL_TYPE_TIMESTAMP: str = "TIMESTAMP"
LOCAL_TYPE_TIMESTAMPTZ: str = "TIMESTAMPTZ"
LOCAL_TYPE_UINT128: str = "UINT128"
LOCAL_TYPE_VARCHAR: str = "VARCHAR"

POSTGRES_SERIAL_TYPES: frozenset[str] = frozenset({"BIGSERIAL", "SERIAL", "SMALLSERIAL"})
POSTGRES_BIGSERIAL_TYPE: str = "BIGSERIAL"
POSTGRES_SMALLSERIAL_TYPE: str = "SMALLSERIAL"
POSTGRES_PARAMETERIZED_TEXT_TYPES: frozenset[str] = frozenset({"VARCHAR", "CHARACTER VARYING"})
POSTGRES_PARAMETERIZED_DECIMAL_TYPES: frozenset[str] = frozenset({"NUMERIC", "DECIMAL"})
POSTGRES_VARCHAR_TYPES: frozenset[str] = frozenset(
    {
        "CIDR",
        "CIRCLE",
        "DATERANGE",
        "INT4RANGE",
        "INT8RANGE",
        "LINE",
        "LSEG",
        "MACADDR",
        "MACADDR8",
        "NAME",
        "NUMRANGE",
        "PATH",
        "POINT",
        "POLYGON",
        "REGCLASS",
        "TSQUERY",
        "TSRANGE",
        "TSTZRANGE",
        "TSVECTOR",
        "VARBIT",
    }
)

SNOWFLAKE_NUMBER_TYPE: str = "NUMBER"
SNOWFLAKE_DOUBLE_TYPES: frozenset[str] = frozenset(
    {"FLOAT", "FLOAT8", "DOUBLE", "DOUBLE PRECISION"}
)
SNOWFLAKE_REAL_TYPE: str = "FLOAT4"
SNOWFLAKE_TIMEZONE_TIMESTAMP_TYPES: frozenset[str] = frozenset({"TIMESTAMP_LTZ", "TIMESTAMP_TZ"})
SNOWFLAKE_TIMESTAMP_NTZ_TYPE: str = "TIMESTAMP_NTZ"
SNOWFLAKE_VECTOR_TYPE: str = "VECTOR"
BIGQUERY_BIGNUMERIC_TYPE: str = "BIGNUMERIC"
BIGQUERY_VARCHAR_TYPES: frozenset[str] = frozenset({"RANGE", "BYTES"})
BIGQUERY_BYTES_TYPE: str = "BYTES"
BIGQUERY_TIMESTAMP_TYPE: str = "TIMESTAMP"
BIGQUERY_WIDEN_TO_DOUBLE_TYPES: frozenset[str] = frozenset({"FLOAT64"})
DATABRICKS_TIMESTAMP_TYPE: str = "TIMESTAMP"
DATABRICKS_TIMESTAMP_NTZ_TYPE: str = "TIMESTAMP_NTZ"
DATABRICKS_VOID_TYPE: str = "VOID"
DUCKDB_HUGEINT_TYPE: str = "HUGEINT"
DUCKDB_UHUGEINT_TYPE: str = "UHUGEINT"
DUCKDB_BLOB_TYPE: str = "BLOB"
DUCKDB_LIST_TYPE: str = "LIST"
DUCKDB_INTEGER_TYPE: str = "INTEGER"

FALLBACK_POLYGLOT_BASE_TYPES: frozenset[str] = frozenset(
    {
        "BOOL",
        "BOOLEAN",
        "TINYINT",
        "SMALLINT",
        "INT",
        "INTEGER",
        "BIGINT",
        "FLOAT",
        "DOUBLE",
        "DECIMAL",
        "NUMERIC",
        "DATE",
        "TIME",
        "TIMESTAMP",
        "DATETIME",
        "VARCHAR",
        "CHAR",
        "TEXT",
        "STRING",
        "JSON",
    }
)
POLYGLOT_DECIMAL_TYPES: frozenset[str] = frozenset({"BIGDECIMAL", "DECIMAL"})
POLYGLOT_VARCHAR_TYPES: frozenset[str] = frozenset({"NULL", "RANGE", "XML"})
POLYGLOT_OBJECT_TYPE: str = "OBJECT"
POLYGLOT_ARRAY_TYPE: str = "ARRAY"
POLYGLOT_COLLECTION_TYPES: frozenset[str] = frozenset({"ARRAY", "LIST"})
POLYGLOT_SPATIAL_AND_MONEY_TYPES: frozenset[str] = frozenset({"GEOGRAPHY", "GEOMETRY", "MONEY"})
POLYGLOT_CUSTOM_TYPE: str = "CUSTOM"

FALLBACK_BOOLEAN_TYPES: frozenset[str] = frozenset({"BOOL", "BOOLEAN"})
FALLBACK_SIGNED_INTEGER_TYPES: frozenset[str] = frozenset(
    {"TINYINT", "SMALLINT", "INT", "INTEGER", "BIGINT", "HUGEINT"}
)
FALLBACK_UNSIGNED_INTEGER_TYPES: frozenset[str] = frozenset(
    {"UTINYINT", "USMALLINT", "UINTEGER", "UBIGINT", "UHUGEINT"}
)
FALLBACK_FLOAT_TYPES: frozenset[str] = frozenset(
    {"FLOAT", "FLOAT4", "REAL", "DOUBLE", "DOUBLE PRECISION", "FLOAT8"}
)
FALLBACK_DECIMAL_TYPES: frozenset[str] = frozenset({"DECIMAL", "DEC", "NUMERIC", "NUMBER"})
FALLBACK_DATE_TYPE: str = "DATE"
FALLBACK_TIME_TYPES: frozenset[str] = frozenset({"TIME", "TIME WITH TIME ZONE", "TIMETZ"})
FALLBACK_TIMESTAMP_TOKEN: str = "TIMESTAMP"
FALLBACK_TIMESTAMP_TYPES: frozenset[str] = frozenset({"DATETIME", "TIMESTAMPTZ"})
FALLBACK_VARCHAR_TYPES: frozenset[str] = frozenset(
    {"VARCHAR", "CHAR", "CHARACTER", "TEXT", "STRING"}
)
FALLBACK_JSON_TYPES: frozenset[str] = frozenset({"JSON", "JSONB"})
FALLBACK_BINARY_TYPES: frozenset[str] = frozenset({"BLOB", "BYTEA", "BINARY", "VARBINARY"})
FALLBACK_STRUCTURED_TYPES: frozenset[str] = frozenset(
    {"ARRAY", "OBJECT", "VARIANT", "JSON", "JSONB"}
)
SNOWFLAKE_WIDEN_TO_DOUBLE_TYPES: frozenset[str] = SNOWFLAKE_DOUBLE_TYPES
GENERIC_WIDEN_TO_DOUBLE_TYPES: frozenset[str] = frozenset({"DOUBLE", "DOUBLE PRECISION", "FLOAT8"})

TYPE_ARGUMENT_OPEN_PAREN: str = "("
TYPE_ARGUMENT_CLOSE_PAREN: str = ")"
TYPE_ARGUMENT_CLOSE_ANGLE: str = ">"
TYPE_ARGUMENT_OPEN_TOKENS: frozenset[str] = frozenset({"(", "<"})
TYPE_ARGUMENT_CLOSE_TOKENS: frozenset[str] = frozenset({")", ">"})
TYPE_ARGUMENT_SEPARATOR: str = ","
TYPE_PATTERN_WILDCARD: str = "*"
MALFORMED_RENDERED_TYPE_TOKEN: str = ")("
UNTYPED_ARRAY_TYPE: str = "[]"
JSONL_BLANK_LINE: str = ""
