"""SQL test executor diagnostic codes."""

SQL_TEST_TOO_LARGE_CODE: str = "T001"
SQL_TEST_EXECUTION_ERROR_CODE: str = "T002"
SQL_TEST_ASSERTION_FAILED_CODE: str = "T003"
SQL_TEST_ENTRY_MISSING_CODE: str = "T004"
SQL_TEST_EXPECTED_COLUMNS_CODE: str = "T005"
SQL_TEST_SIZE_BYTES: str = "bytes"

SQL_TEST_NATIVE_RENDER_WORKERS: int = 4
SQL_TEST_IDENTIFIER_QUOTES: dict[str, str] = {'"': '"', "`": "`", "[": "]"}
