"""Unit tests for linting the expanded SQL a project produces."""

from __future__ import annotations

from pathlib import Path

import pytest

from sqlbuild.compiler.compile.main.expand_sql_with_spans import expand_sql_with_spans
from sqlbuild.compiler.compile.models import SqlExpansionContext
from sqlbuild.lint._helpers.expansion import build_lint_expansion_context
from sqlbuild.lint.exceptions import ProjectCompileError
from sqlbuild.lint.main.run_lint import run_lint
from sqlbuild.lint.models import LintConfig, LintRunResult
from tests.unit.src.sqlbuild.lint._test_types import (
    ExpandedLintTestCase,
    ExpandedTypedConstantTestCase,
    LintCompileFailureTestCase,
    LintProjectTestCase,
)

PROJECT_TOML: str = 'name = "demo"\nadapter = "duckdb"\n'
BAD_COLUMNS_MACRO: str = 'def bad_cols(ctx):\n    return "a,b"\n'
HEADER: str = 'MODEL (\n  materialized table,\n  description "ok"\n);\n'


@pytest.mark.parametrize(
    "test_case",
    [
        ExpandedTypedConstantTestCase(
            description="lint expansion uses configured adapter array rendering",
            project_files={
                "sqlbuild_project.toml": PROJECT_TOML,
                "constants/countries.sql": (
                    'CONSTANT (name countries, value ["GB", "FR"], render_as array);\n'
                ),
                "models/demo.sql": f'{HEADER}SELECT @const("countries") AS countries\n',
            },
            model_path="models/demo.sql",
            authored_sql='SELECT @const("countries") AS countries',
            expected_sql="SELECT ['GB', 'FR'] AS countries",
        ),
        ExpandedTypedConstantTestCase(
            description="lint expansion uses inherited declaration visibility",
            project_files={
                "sqlbuild_project.toml": PROJECT_TOML,
                "models/domain/_constants/value.sql": "CONSTANT (name value, value 9);\n",
                "models/domain/child/demo.sql": f'{HEADER}SELECT @const("value") AS value\n',
            },
            model_path="models/domain/child/demo.sql",
            authored_sql='SELECT @const("value") AS value',
            expected_sql="SELECT 9 AS value",
        ),
        ExpandedTypedConstantTestCase(
            description="lint expansion uses expected model declaration grants",
            project_files={
                "sqlbuild_project.toml": PROJECT_TOML,
                "models/domain/_constants/value.sql": "CONSTANT (name value, value 12);\n",
                "models/domain/orders.sql": f"{HEADER}SELECT 1 AS value\n",
                "tests/unit/other/orders.sql": (
                    "TEST ();\nWITH __expected__orders AS "
                    '(SELECT @const("value") AS value) SELECT 1\n'
                ),
            },
            model_path="tests/unit/other/orders.sql",
            authored_sql=('WITH __expected__orders AS (SELECT @const("value") AS value) SELECT 1'),
            expected_sql="WITH __expected__orders AS (SELECT 12 AS value) SELECT 1",
        ),
    ],
    ids=lambda case: case.description,
)
def test_given_typed_constant_when_building_lint_context_then_uses_adapter_rendering(
    test_case: ExpandedTypedConstantTestCase,
    tmp_path: Path,
) -> None:
    for relative_path, contents in test_case.project_files.items():
        target: Path = tmp_path / relative_path
        _ = target.parent.mkdir(parents=True, exist_ok=True)
        _ = target.write_text(contents, encoding="utf-8")
    context: SqlExpansionContext = build_lint_expansion_context(project_dir=tmp_path)

    expanded_sql, _passes = expand_sql_with_spans(
        sql=test_case.authored_sql,
        file_path=tmp_path / test_case.model_path,
        context=context,
    )

    assert expanded_sql == test_case.expected_sql


@pytest.mark.parametrize(
    "test_case",
    [
        ExpandedLintTestCase(
            description="diagnostic inside macro output is attributed to the call site",
            project_files={
                "sqlbuild_project.toml": PROJECT_TOML,
                "macros/m.py": BAD_COLUMNS_MACRO,
                "models/demo.sql": f"{HEADER}SELECT @bad_cols() FROM t\n",
            },
            expected_positions=((5, 8),),
            expected_message_fragments=("in SQL generated by @bad_cols()",),
        ),
        ExpandedLintTestCase(
            description="diagnostic in authored SQL keeps its exact position",
            project_files={
                "sqlbuild_project.toml": PROJECT_TOML,
                "models/demo.sql": f"{HEADER}SELECT a,b FROM t\n",
            },
            expected_positions=((5, 10),),
            expected_message_fragments=(),
        ),
        ExpandedLintTestCase(
            description="unbound audit parameter is linted without a parse failure",
            project_files={
                "sqlbuild_project.toml": PROJECT_TOML,
                "audits/generic/expr.sql": (
                    'AUDIT ();\n\nSELECT *\nFROM __ref("@model")\nWHERE NOT (@expression)\n'
                ),
            },
            expected_positions=(),
            expected_message_fragments=(),
        ),
        ExpandedLintTestCase(
            description="model-local declarations expand in their owning model",
            project_files={
                "sqlbuild_project.toml": PROJECT_TOML,
                "models/demo.sql": (
                    'MODEL (\n  description "ok",\n'
                    "  enums (_status [A]),\n"
                    "  constants (_limit 1)\n);\n"
                    'SELECT @enum("_status").A AS status, @const("_limit") AS amount\n'
                ),
            },
            expected_positions=(),
            expected_message_fragments=(),
        ),
    ],
    ids=lambda case: case.description,
)
def test_given_project_when_linting_expanded_sql_then_positions_are_authored(
    test_case: ExpandedLintTestCase, tmp_path: Path
) -> None:
    relative_path: str
    contents: str
    for relative_path, contents in test_case.project_files.items():
        target: Path = tmp_path / relative_path
        _ = target.parent.mkdir(parents=True, exist_ok=True)
        _ = target.write_text(contents, encoding="utf-8")
    result: LintRunResult = run_lint(project_dir=tmp_path, config=LintConfig(sqruff_enabled=True))
    positions: tuple[tuple[int, int], ...] = tuple(
        (violation.line, violation.column) for violation in result.violations
    )
    expected_position: tuple[int, int]
    for expected_position in test_case.expected_positions:
        assert expected_position in positions
    messages: str = " ".join(violation.message for violation in result.violations)
    fragment: str
    for fragment in test_case.expected_message_fragments:
        assert fragment in messages


@pytest.mark.parametrize(
    "test_case",
    [
        LintCompileFailureTestCase(
            description="missing project config fails instead of linting a fiction",
            project_files={"models/demo.sql": f"{HEADER}SELECT 1 AS x FROM t\n"},
            expected_message_fragment="must compile first",
        ),
        LintCompileFailureTestCase(
            description="missing env variable in SQL fails with the variable named",
            project_files={
                "sqlbuild_project.toml": PROJECT_TOML,
                "models/demo.sql": f"{HEADER}SELECT 1 AS x FROM @@ENV:SQLBUILD_ABSENT_VAR\n",
            },
            expected_message_fragment="SQLBUILD_ABSENT_VAR",
        ),
        LintCompileFailureTestCase(
            description="unsupported project module imports fail before lint expansion",
            project_files={
                "sqlbuild_project.toml": PROJECT_TOML,
                "macros/orders.py": "import macros.shared\n",
                "macros/shared.py": "def shared_macro() -> str:\n    return 'order_id'\n",
                "models/demo.sql": f"{HEADER}SELECT 1 AS x\n",
            },
            expected_message_fragment="module imports are not supported",
        ),
        LintCompileFailureTestCase(
            description="inaccessible declaration fails lint with compile visibility diagnostic",
            project_files={
                "sqlbuild_project.toml": PROJECT_TOML,
                "models/one/_constants/value.sql": "CONSTANT (name value, value 1);\n",
                "models/two/demo.sql": f'{HEADER}SELECT @const("value") AS value\n',
            },
            expected_message_fragment="known but inaccessible",
        ),
    ],
    ids=lambda case: case.description,
)
def test_given_uncompilable_project_when_linting_then_it_fails_clearly(
    test_case: LintCompileFailureTestCase, tmp_path: Path
) -> None:
    relative_path: str
    contents: str
    for relative_path, contents in test_case.project_files.items():
        target: Path = tmp_path / relative_path
        _ = target.parent.mkdir(parents=True, exist_ok=True)
        _ = target.write_text(contents, encoding="utf-8")
    with pytest.raises(ProjectCompileError) as error:
        _ = run_lint(project_dir=tmp_path, config=LintConfig(sqruff_enabled=True))
    assert test_case.expected_message_fragment in str(error.value)


@pytest.mark.parametrize(
    "test_case",
    [
        LintProjectTestCase(
            description="canonical scenario header is accepted by lint and compile",
            files={
                "sqlbuild_project.toml": PROJECT_TOML,
                "tests/scenarios/example.sql": (
                    'SCENARIO (description "Contains: a colon", tags [yes, on]);\nSELECT 1\n'
                ),
            },
            sqruff_enabled=True,
            expected_fault_codes=(),
        )
    ],
    ids=lambda case: case.description,
)
def test_given_canonical_scenario_header_when_linting_and_compiling_then_both_accept_it(
    tmp_path: Path,
    test_case: LintProjectTestCase,
) -> None:
    for relative_path, contents in test_case.files.items():
        target: Path = tmp_path / relative_path
        _ = target.parent.mkdir(parents=True, exist_ok=True)
        _ = target.write_text(contents, encoding="utf-8")

    result: LintRunResult = run_lint(
        project_dir=tmp_path,
        config=LintConfig(sqruff_enabled=test_case.sqruff_enabled),
    )

    assert (
        tuple((violation.file_path.as_posix(), violation.code) for violation in result.violations)
        == test_case.expected_fault_codes
    )
