"""Real-CLI coverage for SQBRSQL045, a JSON payload parsed more than once in one SELECT."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from sqlbuild.cli.commands.main.entrypoint.entry import main
from tests.integration.src.sqlbuild.cli.commands.main._test_types import (
    RepeatedJsonParseTestCase,
)
from tests.integration.src.sqlbuild.cli.commands.main.helpers import (
    write_repeated_json_parse_project,
)

_DUCKDB_HEADER: str = 'MODEL (description "Order events");\n'
_SNOWFLAKE_HEADER: str = (
    'MODEL (description "Order events", database warehouse, schema analytics);\n'
)
_DUCKDB_EVENTS: str = "WITH events AS (SELECT 1 AS event_id, '{\"order_id\": 1}' AS payload),\n"


@pytest.mark.parametrize(
    "test_case",
    [
        RepeatedJsonParseTestCase(
            description="duckdb payload parsed per field",
            adapter="duckdb",
            header=_DUCKDB_HEADER,
            sql=(
                f"{_DUCKDB_EVENTS}"
                "final AS (\n"
                "  SELECT\n"
                "    e.event_id,\n"
                "    json(e.payload)->>'order_id' AS order_id,\n"
                "    json(e.payload)->>'status' AS status\n"
                "  FROM events AS e\n"
                ")\n"
                "SELECT event_id, order_id, status FROM final\n"
            ),
            expected_locations=((7, 5),),
            expected_detail="JSON(e.payload) is parsed 2 times in one SELECT.",
        ),
        RepeatedJsonParseTestCase(
            description="repeat generated by a macro is located at the macro call",
            adapter="duckdb",
            header=_DUCKDB_HEADER,
            sql=(
                f"{_DUCKDB_EVENTS}"
                "final AS (\n"
                "  SELECT\n"
                "    e.event_id,\n"
                "    json(e.payload)->>'status' AS status,\n"
                "    @order_id_field() AS order_id\n"
                "  FROM events AS e\n"
                ")\n"
                "SELECT event_id, order_id, status FROM final\n"
            ),
            expected_locations=((7, 5),),
            expected_detail="JSON(e.payload) is parsed 2 times in one SELECT.",
            extra_files=(
                (
                    "macros/fields.py",
                    "def order_id_field(ctx):\n    return \"json(e.payload)->>'order_id'\"\n",
                ),
            ),
        ),
        RepeatedJsonParseTestCase(
            description="duckdb payload parsed once in its own CTE",
            adapter="duckdb",
            header=_DUCKDB_HEADER,
            sql=(
                f"{_DUCKDB_EVENTS}"
                "parsed AS (SELECT e.event_id, json(e.payload) AS payload FROM events AS e),\n"
                "final AS (\n"
                "  SELECT\n"
                "    p.event_id,\n"
                "    p.payload->>'order_id' AS order_id,\n"
                "    p.payload->>'status' AS status\n"
                "  FROM parsed AS p\n"
                ")\n"
                "SELECT event_id, order_id, status FROM final\n"
            ),
            expected_locations=(),
        ),
    ],
    ids=lambda case: case.description,
)
def test_given_json_parses_when_compiling_and_running_rules_then_repeats_fail_at_second_parse(
    test_case: RepeatedJsonParseTestCase, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    write_repeated_json_parse_project(tmp_path=tmp_path, test_case=test_case)
    expected_exit_code: int = int(bool(test_case.expected_locations))

    assert main(["--project-dir", str(tmp_path), "compile", "--no-cache"]) == expected_exit_code
    capsys.readouterr()
    result: int = main(["--project-dir", str(tmp_path), "rules", "--json", "run", "SQBRSQL045"])
    findings: list[dict[str, object]] = json.loads(capsys.readouterr().out)["findings"]

    assert result == expected_exit_code
    assert tuple((finding["line"], finding["column"]) for finding in findings) == (
        test_case.expected_locations
    )
    assert all(
        str(finding["remediation"]).startswith(test_case.expected_detail) for finding in findings
    )
    assert all(
        "parse it once" in str(finding["remediation"]).lower()
        and "AS payload" in str(finding["remediation"])
        for finding in findings
    )


@pytest.mark.parametrize(
    "test_case",
    [
        RepeatedJsonParseTestCase(
            description="snowflake try parse repeated in a filter",
            adapter="snowflake",
            header=_SNOWFLAKE_HEADER,
            sql=(
                "SELECT TRY_PARSE_JSON(e.value):order_id AS order_id\n"
                "FROM raw_events AS e\n"
                "WHERE TRY_PARSE_JSON(e.value):status = 'shipped'\n"
            ),
            expected_locations=((4, 7),),
            expected_detail="TRY_PARSE_JSON(e.value) is parsed 2 times in one SELECT.",
        ),
        RepeatedJsonParseTestCase(
            description="snowflake parse and try parse are different calls",
            adapter="snowflake",
            header=_SNOWFLAKE_HEADER,
            sql=(
                "SELECT TRY_PARSE_JSON(e.value):order_id AS order_id\n"
                "FROM raw_events AS e\n"
                "WHERE PARSE_JSON(e.value):status = 'shipped'\n"
            ),
            expected_locations=(),
        ),
    ],
    ids=lambda case: case.description,
)
def test_given_snowflake_json_parses_when_running_rules_then_repeats_are_reported_offline(
    test_case: RepeatedJsonParseTestCase, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    write_repeated_json_parse_project(tmp_path=tmp_path, test_case=test_case)

    result: int = main(["--project-dir", str(tmp_path), "rules", "--json", "run", "SQBRSQL045"])
    findings: list[dict[str, object]] = json.loads(capsys.readouterr().out)["findings"]

    assert result == int(bool(test_case.expected_locations))
    assert tuple((finding["line"], finding["column"]) for finding in findings) == (
        test_case.expected_locations
    )
    assert all(
        str(finding["remediation"]).startswith(test_case.expected_detail) for finding in findings
    )


if __name__ == "__main__":
    pytest.main([__file__, "-vv"])
